### ISSUE TITLE
希望能出个详细教程

### ISSUE THREAD

**Issue by Y-pandaman** [xubiaolin/docker-zerotier-planet#1]
希望能出个详细教程

**Comment by xubiaolin** [comment]
我再优化一下，这周日就出个文档。

**Comment by Y-pandaman** [comment]
666

从 Windows 版邮件发送

发件人: Markxu
发送时间: 2021年11月19日 15:15
收件人: xubiaolin/docker-zerotier-planet
抄送: pandaman; Author
主题: Re: [xubiaolin/docker-zerotier-planet] 希望能出个详细教程 (Issue #1)

我再优化一下，这周日就出个文档。
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xubiaolin** [comment]
文档已出

**Comment by Y-pandaman** [comment]
请问在云服务器上同时布置moon节点和您这个planet节点，会冲突吗？
