### ISSUE TITLE
Possible Changes For The Code

### ISSUE THREAD

**Issue by xutongtongxue** [xubiaolin/docker-zerotier-planet#10]
Hi xubiaoliln,

Thanks for your efforts to the project.

I just readed your source code. Maybe there are some new changes that can be added to the code. Some of the features that migth 
 be benefits to the code/user are shown below.

1. Automatically get the current public IP , no longer need to change the patch.json when generating the image. Some of APIs can be used, such as:
    http://ip.3322.net/
    https://httpbin.org/ip
    https://pv.sohu.com/cityjson?ie=utf-8
    http://whois.pconline.com.cn/ipJson.jsp
    http://v4.ipv6-test.com/api/myip.php
    https://api-ipv4.ip.sb/ip
    http://myip.ipip.net/s

2. mkworld.cpp file clone from the offical repos in real time in order to prevent file content changes from causing the generation to fail.

That's all, thank you.

**Comment by xubiaolin** [comment]
Thanks for your suggestions, I will add these features later.
