### ISSUE TITLE
望大佬能修改一下代码添加代码直接从源码编译，这样就不用受制于人编译出与官方同步的ZeroTie

### ISSUE THREAD

**Issue by MINGERTAI** [xubiaolin/docker-zerotier-planet#101]
望大佬能修改一下代码，谢谢了。希望能添加代码直接从源码编译，这样就不用受制于人，只要官方更新了源码，我们这编译出来的也是最新的

**Comment by MINGERTAI** [comment]
我用他家的tiredofit的 https://github.com/tiredofit/docker-alpine/pkgs/container/docker-alpine/150643446?tag=latest 替换 FROM ghcr.io/tiredofit/docker-alpine:latest 出错，是不是他家的也是没有alpine编译的ZeroTier

**Comment by MINGERTAI** [comment]
望大佬能修改一下代码，谢谢了。希望能添加代码直接从源码编译，这样就不用受制于人，只要官方更新了源码，我们这编译出来的也是最新的

**Comment by xubiaolin** [comment]
嗯嗯，现在的问题主要是从源码编译比较慢，正在尝试优化编译时间

**Comment by MINGERTAI** [comment]
我现在尝试自动划取最新版本号
RUN ZEROTIER_ONE_VERSION=`curl -s "https://api.github.com/repos/zerotier/ZeroTierOne/releases" | jq '.[0].tag_name'` && \
    curl https://codeload.github.com/zerotier/ZeroTierOne/tar.gz/refs/tags/${ZEROTIER_ONE_VERSION} --output /tmp/ZeroTierOne.tar.gz \
    && tar fxz /tmp/ZeroTierOne.tar.gz \
    && mv /app/ZeroTierOne-* /app/ZeroTierOne \
    && rm -rf /tmp/ZeroTierOne.tar.gz \
    && cd /app/ZeroTierOne \
    && make ZT_SYMLINK=1 \
    && make install

**Comment by MINGERTAI** [comment]
加版本号，编译成功

**Comment by xubiaolin** [comment]
免编译镜像测试已通过，这两天会整理代码和镜像，大家不用折腾编译了

**Comment by xubiaolin** [comment]
ZT_PORT=9994
API_PORT=3443
FILE_PORT=3000

docker run -d --name myztplanet\
     -p ${ZT_PORT}:${ZT_PORT} \
     -p ${ZT_PORT}:${ZT_PORT}/udp \
     -p ${API_PORT}:${API_PORT}\
     -p ${FILE_PORT}:${FILE_PORT} \
     -e ZT_PORT=${ZT_PORT} \
     -e API_PORT=${API_PORT} \
     -e FILE_SERVER_PORT=${FILE_PORT} \
     -v /data/zerotier/dist:/app/dist \
     -v /data/zerotier/ztncui:/app/ztncui\
     -v /data/zerotier/one:/var/lib/zerotier-one\
     -v /data/config:/app/config\
     xubiaolin/zerotier-planet:latest

**Comment by xubiaolin** [comment]
最新代码已发布，支持了1.12.2版本
