### ISSUE TITLE
因为要本地编译，所以时间稍长，你是国内还是国外服务器呢？

### ISSUE THREAD

**Issue by MINGERTAI** [xubiaolin/docker-zerotier-planet#103]
因为要本地编译，所以时间稍长，你是国内还是国外服务器呢？

> > > > 最新代码已改为从官方最新代码编译zerotier了，请使用最新的脚本部署
> > > 
> > > 
> > > 大佬，最新脚本怎么获取？ 使用 git clone https://github.com/xubiaolin/docker-zerotier-planet.git 安装还是1.10.2，使用全新debian12.2系统安装 谢谢
> > 
> > 
> > 试下用这个安装呢？https://github.com/wekingchen/docker-zerotier-planet
> 
> 上午重试了一下，一次安装成功 1.12.2，就是安装时间稍长。

终于有人成功了，哈哈。因为要在本地编译，所以时间稍长，你是国内还是国外服务器呢？

_Originally posted by @wekingchen in https://github.com/xubiaolin/docker-zerotier-planet/issues/94#issuecomment-1826712416_
       
https://github.com/sbilly/docker-zerotier-controller 他这个是下载源压缩包的，我也觉得直接拉取源文件还是下载包快，另外他RUN ZERO_UI_VERSION=`curl --silent "https://api.github.com/repos/dec0dOS/zero-ui/tags" | jq -r '.[0].name'`引用变量，使编译出的版本为最新的，我有测试，依样画葫芦的，但是编译时出错

**Comment by xubiaolin** [comment]
我已经测试通过了源码编译，即将更新免编译版本，请等待1-2天

**Comment by xubiaolin** [comment]
ZT_PORT=9994
API_PORT=3443
FILE_PORT=3000

docker run -d --name myztplanet\
     -p ${ZT_PORT}:${ZT_PORT} \
     -p ${ZT_PORT}:${ZT_PORT}/udp \
     -p ${API_PORT}:${API_PORT}\
     -p ${FILE_PORT}:${FILE_PORT} \
     -e ZT_PORT=${ZT_PORT} \
     -e API_PORT=${API_PORT} \
     -e FILE_SERVER_PORT=${FILE_PORT} \
     -v /data/zerotier/dist:/app/dist \
     -v /data/zerotier/ztncui:/app/ztncui\
     -v /data/zerotier/one:/var/lib/zerotier-one\
     -v /data/config:/app/config\
     xubiaolin/zerotier-planet:latest

**Comment by xubiaolin** [comment]
最新代码已发布，支持了1.12.2版本
