### ISSUE TITLE
> 大佬，按照你readme的步骤去走docker安装完成后还是显示版本为1.10.2，我看您在评论中说改为1.12.2了，是什么原因呢？

### ISSUE THREAD

**Issue by MINGERTAI** [xubiaolin/docker-zerotier-planet#104]
> 大佬，按照你readme的步骤去走docker安装完成后还是显示版本为1.10.2，我看您在评论中说改为1.12.2了，是什么原因呢？

上次的更新有点问题，回退了，近期就会更新

_Originally posted by @xubiaolin in https://github.com/xubiaolin/docker-zerotier-planet/issues/94#issuecomment-1846598697_

更新新代码，要好用很麻烦是吧？

**Comment by xubiaolin** [comment]
ZT_PORT=9994
API_PORT=3443
FILE_PORT=3000

docker run -d --name myztplanet\
     -p ${ZT_PORT}:${ZT_PORT} \
     -p ${ZT_PORT}:${ZT_PORT}/udp \
     -p ${API_PORT}:${API_PORT}\
     -p ${FILE_PORT}:${FILE_PORT} \
     -e ZT_PORT=${ZT_PORT} \
     -e API_PORT=${API_PORT} \
     -e FILE_SERVER_PORT=${FILE_PORT} \
     -v /data/zerotier/dist:/app/dist \
     -v /data/zerotier/ztncui:/app/ztncui\
     -v /data/zerotier/one:/var/lib/zerotier-one\
     -v /data/config:/app/config\
     xubiaolin/zerotier-planet:latest

**Comment by xubiaolin** [comment]
最新代码已发布，支持了1.12.2版本
