### ISSUE TITLE
请问大佬，有没有已经编译好了的docker镜像

### ISSUE THREAD

**Issue by spysir** [xubiaolin/docker-zerotier-planet#105]
如果有已经编译好了的docker镜像就方便多了

**Comment by xubiaolin** [comment]
ZT_PORT=9994
API_PORT=3443
FILE_PORT=3000

docker run -d --name myztplanet\
     -p ${ZT_PORT}:${ZT_PORT} \
     -p ${ZT_PORT}:${ZT_PORT}/udp \
     -p ${API_PORT}:${API_PORT}\
     -p ${FILE_PORT}:${FILE_PORT} \
     -e ZT_PORT=${ZT_PORT} \
     -e API_PORT=${API_PORT} \
     -e FILE_SERVER_PORT=${FILE_PORT} \
     -v /data/zerotier/dist:/app/dist \
     -v /data/zerotier/ztncui:/app/ztncui\
     -v /data/zerotier/one:/var/lib/zerotier-one\
     -v /data/config:/app/config\
     xubiaolin/zerotier-planet:latest
     
     
    有的，只是交互脚本没时间写

**Comment by spysir** [comment]
> ZT_PORT=9994 API_PORT=3443 FILE_PORT=3000
> 
> docker run -d --name myztplanet -p ${ZT_PORT}:${ZT_PORT} -p ${ZT_PORT}:${ZT_PORT}/udp -p ${API_PORT}:${API_PORT} -p ${FILE_PORT}:${FILE_PORT} -e ZT_PORT=${ZT_PORT} -e API_PORT=${API_PORT} -e FILE_SERVER_PORT=${FILE_PORT} -v /data/zerotier/dist:/app/dist -v /data/zerotier/ztncui:/app/ztncui -v /data/zerotier/one:/var/lib/zerotier-one -v /data/config:/app/config xubiaolin/zerotier-planet:latest
> 
> ```
> 有的，只是交互脚本没时间写
> ```

已经搞定，多谢指点
