### ISSUE TITLE
无法加入自建的planet

### ISSUE THREAD

**Issue by spysir** [xubiaolin/docker-zerotier-planet#107]

**Comment by xubiaolin** [comment]
zyclonite/zerotier:latest 这个不是我的镜像

**Comment by spysir** [comment]
> zyclonite/zerotier:latest 这个不是我的镜像

不好意思，刚才那个搞错了，是你这个xubiaolin/zerotier-planet:latest

**Comment by spysir** [comment]
planet文件路径是/var/lib/zerotier-one吗

**Comment by xubiaolin** [comment]
你重启客户端了吗？

**Comment by xubiaolin** [comment]
加qq群或者tg吧，群里面问更方便
