### ISSUE TITLE
planet 文件没有找到

### ISSUE THREAD

**Issue by wekingchen** [xubiaolin/docker-zerotier-planet#111]
新版docker安装完成后，没有找到/data/zerotier/dist文件夹呢？

**Comment by xubiaolin** [comment]
在你宿主机上的/data/zerotier/dist目录，截图看看

**Comment by wekingchen** [comment]
![image](https://github.com/xubiaolin/docker-zerotier-planet/assets/22815621/d033a70b-ba57-4efe-943e-f0020a6aed9a)
看设定上是的确是挂载到我宿主机上的/data/zerotier/dist目录，但是我宿主机上原本没有这个data目录，用新脚本安装之后也没有自动生成这个目录呢？

**Comment by xubiaolin** [comment]
执行命令 ls /data/zerotier/dist试试看

**Comment by wekingchen** [comment]
![image](https://github.com/xubiaolin/docker-zerotier-planet/assets/22815621/83dffa93-3e91-4589-8332-78ecd5d25d19)

**Comment by xubiaolin** [comment]
那你试试先创建/data目录，然后重新部署下试试

**Comment by wekingchen** [comment]
试过在根目录先创建data目录，部署后也没有挂载进去，我最后手动用docker cp myztplanet:/app/dist /home/dist的方式拷贝出来的

**Comment by xubiaolin** [comment]
看起来像是权限问题，可以修改脚本，挂载到项目的路径下

**Comment by wekingchen** [comment]
那麻烦大大改一下脚本

**Comment by xubiaolin** [comment]
你是用的root权限执行的吗？

**Comment by xubiaolin** [comment]
脚本已修改，你拉下最新代码试试

**Comment by wekingchen** [comment]
我是root帐号运行的，新代码安装失败：
![image](https://github.com/xubiaolin/docker-zerotier-planet/assets/22815621/ea559344-4dae-4803-97cd-cdc4c47019b6)

**Comment by xubiaolin** [comment]
已修复，再试试看

**Comment by wekingchen** [comment]
可以了，成功在源码目录下创建data文件夹了~谢谢！

**Comment by wekingchen** [comment]
另外一个小建议，能否在选择创建FILE端口号时，加一个放弃的选择呢？为了安全并不想开放一个下载端口

**Comment by Moe-L** [comment]
新的安装后 moon文件有的,planet文件还是不存在 日志有报错
`+ mv world.bin /app/dist/planet
mv: can't rename 'world.bin': No such file or directory`

**Comment by xubiaolin** [comment]
> 另外一个小建议，能否在选择创建FILE端口号时，加一个放弃的选择呢？为了安全并不想开放一个下载端口

防火墙不放行即可

**Comment by xubiaolin** [comment]
> 新的安装后 moon文件有的,planet文件还是不存在 日志有报错 `+ mv world.bin /app/dist/planet mv: can't rename 'world.bin': No such file or directory`

能留个联系方式吗，或者加qq群，我远程 给你看看

**Comment by wekingchen** [comment]
> > 另外一个小建议，能否在选择创建FILE端口号时，加一个放弃的选择呢？为了安全并不想开放一个下载端口
> 
> 防火墙不放行即可

好多服务器默认没有防火墙，端口都是开放的哦

**Comment by Moe-L** [comment]
> > 新的安装后 moon文件有的,planet文件还是不存在 日志有报错 `+ mv world.bin /app/dist/planet mv: can't rename 'world.bin': No such file or directory`
> 
> 能留个联系方式吗，或者加qq群，我远程 给你看看

非常感谢,已通过重装更换了一个系统解决

**Comment by martint028** [comment]
> > > 新的安装后 moon文件有的,planet文件还是不存在 日志有报错 `+ mv world.bin /app/dist/planet mv: can't rename 'world.bin': No such file or directory`
> > 
> > 
> > 能留个联系方式吗，或者加qq群，我远程 给你看看
> 
> 非常感谢,已通过重装更换了一个系统解决

check_file_server
'[' '!' -f /app/config/file_server.port ]
echo 'file_server.port is not exist, generate it'
echo 3000
echo 3000
check_ztncui
mkdir -p /app/ztncui
file_server.port is not exist, generate it
3000
ls -A /app/ztncui
'[' ]
echo '/app/ztncui is empty, init data'
cp -r /bak/ztncui/LICENSE /bak/ztncui/README.md /bak/ztncui/build /bak/ztncui/src /app/ztncui/
/app/ztncui is empty, init data
echo 'config ztncui'
mkdir -p /app/config
config ztncui
echo 3443
cd /app/ztncui/src
echo 'HTTP_PORT=3443'
echo 'NODE_ENV=production'
echo 'HTTP_ALL_INTERFACES=true'
echo 'ZT_ADDR=localhost:9994'
echo 9994
cp -v etc/default.passwd etc/passwd
'etc/default.passwd' -> 'etc/passwd'
cat /var/lib/zerotier-one/authtoken.secret
cat: can't open '/var/lib/zerotier-one/authtoken.secret': No such file or directory
TOKEN=
check_zerotier
mkdir -p /var/lib/zerotier-one
ls -A /var/lib/zerotier-one
'[' ]
mkdir -p /app/config
echo '/var/lib/zerotier-one is empty, init data'
echo 9994
cp -r /bak/zerotier-one/authtoken.secret /bak/zerotier-one/controller.d /bak/zerotier-one/identity.public /bak/zerotier-one/identity.secret /bak/zerotier-one/metrics.prom /bak/zerotier-one/metricstoken.secret /bak/zerotier-one/planet /bak/zerotier-one/zerotier-cli /bak/zerotier-one/zerotier-idtool /bak/zerotier-one/zerotier-one /bak/zerotier-one/zerotier-one.pid /bak/zerotier-one/zerotier-one.port /bak/zerotier-one/zerotier-one.te /var/lib/zerotier-one/
/var/lib/zerotier-one is empty, init data
cd /var/lib/zerotier-one
echo 'start mkmoonworld'
./zerotier-idtool initmoon identity.public
start mkmoonworld
'[' -z ]
curl -s https://ipv4.icanhazip.com/
IP_ADDR4=81.70.11.200
'[' -z ]
curl -s https://ipv6.icanhazip.com/
IP_ADDR6=
echo 'IP_ADDR4=81.70.11.200'
echo 'IP_ADDR6='
cat /app/config/zerotier-one.port
IP_ADDR4=81.70.11.200
IP_ADDR6=
ZT_PORT=9994
cat /app/config/ztncui.port
API_PORT=3443
echo 'ZT_PORT=9994'
echo 'API_PORT=3443'
'[' -z 81.70.11.200 ]
'[' -z ]
stableEndpoints='["81.70.11.200/9994"]'
'[' -n 81.70.11.200 ]
'[' -n ]
'[' -z 81.70.11.200 ]
echo 81.70.11.200
echo
echo 'stableEndpoints=["81.70.11.200/9994"]'
jq --argjson newEndpoints '["81.70.11.200/9994"]' '.roots[0].stableEndpoints = $newEndpoints' moon.json
ZT_PORT=9994
API_PORT=3443
stableEndpoints=["81.70.11.200/9994"]
mv temp.json moon.json
./zerotier-idtool genmoon moon.json
wrote 00000093caa675b0.moon (signed world with timestamp 1703769423877)
mkdir -p moons.d
cp ./00000093caa675b0.moon ./moons.d
wget https://ghproxy.markxu.online/https://github.com/kaaass/ZeroTierOne/releases/download/mkmoonworld-1.0/mkmoonworld-x86_64
Connecting to ghproxy.markxu.online (38.47.124.28:443)
saving to 'mkmoonworld-x86_64'
mkmoonworld-x86_64 4% |* | 223k 0:00:21 ETA
mkmoonworld-x86_64 55% |***************** | 2767k 0:00:01 ETA
mkmoonworld-x86_64 100% |********************************| 5007k 0:00:00 ETA
'mkmoonworld-x86_64' saved
chmod +x ./mkmoonworld-x86_64
./mkmoonworld-x86_64 moon.json
FATAL: kernel too old
Aborted (core dumped)
mkdir -p /app/dist/
mv world.bin /app/dist/planet
mv: can't rename 'world.bin': No such file or directory
cp 00000093caa675b0.moon /app/dist/
echo -e 'mkmoonworld success!\n'
start
echo 'start ztncui and zerotier'
cd /var/lib/zerotier-one
cat /app/config/zerotier-one.port
mkmoonworld success!

同样报错导致没有 planet, 系统 centos, docker 升级到了最新,用的 root 创建, 尝试了好几遍都是这样
