### ISSUE TITLE
部署完成后moon文件有生成和可以下载,但是planet文件未生成成功!

### ISSUE THREAD

**Issue by wb1t** [xubiaolin/docker-zerotier-planet#122]
部署完成后moon文件有生成和可以下载,但是planet文件未生成成功!

**Comment by xubiaolin** [comment]
> 部署完成后moon文件有生成和可以下载,但是planet文件未生成成功!

centos不支持，内核太低

**Comment by xubiaolin** [comment]
> 而且脚本写的有问题，信息输出报错 key=cat: can't open '/app/config/file_server.key': No such file or directory

什么系统，什么时候报错的错，不要让我的字打的比你多

**Comment by canghaiwuhen** [comment]
> > 而且脚本写的有问题，信息输出报错 key=cat: can't open '/app/config/file_server.key': No such file or directory
> 
> 什么系统，什么时候报错的错，不要让我的字打的比你多

ubuntu 2004
24年1月19日凌晨测试的，刚刚再次测试：
moon配置和planet配置在 /root/docker-zerotier-planet/data/zerotier/dist 目录下
moons 文件下载： http://xxxx:xxxx/?key=cat: can't open '/app/config/file_server.key': No such file or directory   
planet文件下载： http://xxxx:xxxx/planet?key=cat: can't open '/app/config/file_server.key': No such file or directory

**Comment by canghaiwuhen** [comment]
内核版本：Linux Portainer 5.4.0-171-generic #189-Ubuntu SMP Fri Jan 5 14:23:02 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by xubiaolin** [comment]
> 操作很简单 git clone到/root/docker-zerotier-planet 然后./deploy.sh安装

把docker logs myztplanet 的日志全部发来看看，可以的话进tg群或者qq群交流

**Comment by canghaiwuhen** [comment]
> > 操作很简单 git clone到/root/docker-zerotier-planet 然后./deploy.sh安装
> 
> 把docker logs myztplanet 的日志全部发来看看，可以的话进tg群或者qq群交流

加群了，planet问题应该出在这里

```
+ wget https://ghproxy.markxu.online/https://github.com/kaaass/ZeroTierOne/releases/download/mkmoonworld-1.0/mkmoonworld-x86_64
Connecting to ghproxy.markxu.online (38.47.124.28:443)
ssl_client: ghproxy.markxu.online: handshake failed: No error information
wget: error getting response: Connection reset by peer
+ chmod +x ./mkmoonworld-x86_64
chmod: ./mkmoonworld-x86_64: No such file or directory
+ ./mkmoonworld-x86_64 moon.json
/app/entrypoint.sh: line 68: ./mkmoonworld-x86_64: not found
```

can't open '/app/config/file_server.key': No such file or directory
问题应该加个延迟就能解决
后续再执行脚本获取信息能正常显示
