### ISSUE TITLE
如何在从 1.x 更新至 2.0 版本中迁移数据

### ISSUE THREAD

**Issue by spencerwooo** [xubiaolin/docker-zerotier-planet#123]
请问，如果拉取最新代码后，执行 deploy，并选择 `安装` 或 `更新` 来部署 2.0 版本的项目，在已有 1.x 版本（https://github.com/xubiaolin/docker-zerotier-planet/commit/f7448f4cf3eebf792ae59506969ad97c0639ba9a 版本）部署的情况下，如何将原有数据进行迁移？或者说只能重新部署？

**Comment by xubiaolin** [comment]
1.x迁移到2.x比较复杂，暂不支持，建议重新部署

**Comment by spencerwooo** [comment]
好的，感谢解惑
