### ISSUE TITLE
centos 安装 Error response from daemon

### ISSUE THREAD

**Issue by lunckymeet** [xubiaolin/docker-zerotier-planet#124]
centos执行安装脚本，报错Error response from daemon: container 497b9877d9796e307801bc45e26c963b6059c598ab9c17d1150f1266164949cf is not running
![image](https://github.com/xubiaolin/docker-zerotier-planet/assets/63490239/1991707e-8ce0-4a8d-a66f-0186c13005c7)

**Comment by ShaoMings** [comment]
看docker日志应该是centos的内核版本需要升级，安装说明有说到，不想升级用ubuntu吧

**Comment by xubiaolin** [comment]
centos等低版本内核近期将会支持上，请耐心等候

**Comment by xubiaolin** [comment]
CentOS已支持，请拉取最新代码重试
