### ISSUE TITLE
是否考虑集成 zero-ui

### ISSUE THREAD

**Issue by szzylph** [xubiaolin/docker-zerotier-planet#133]
是否考虑集成 zero-ui,这个可以支持ACL ，与官方的类似

**Comment by xubiaolin** [comment]
感谢你的建议，我对比下ztncui和zero-ui，看看哪个更好用，如果zero-ui更好用的话我会集成进来的

**Comment by chmis8000** [comment]
zero-ui也没好到哪里去，好像一味的模仿官方界面。
登录后台，最常用的功能就是看IP列表，zeroTier的客户端居然不给其他客户IP列表的权限，必须后台查，
ztncui是点击两下鼠标就能看IP列表。
zero-ui是点击一下鼠标看IP列表，但列表在页面下面，需要滚动。

**Comment by szzylph** [comment]
关键是它有 ACL配置界面，不知道ztncui 如何配置ACL权限

**Comment by MINGERTAI** [comment]
我感觉如可以的话，ztncui加上如ztnet这个有一个创建私人planet就非常好了，它这个支持创建多服务器合一的planet，不过应该得在ztncui源代码上添加
