### ISSUE TITLE
项目生成的Moon文件作为moon节点使用后无法连接

### ISSUE THREAD

**Issue by dadastory** [xubiaolin/docker-zerotier-planet#139]
项目生成的moon文件放到moons.d文件夹下，通过zerotier-cli peers显示是无法连接的，通过几个客户端都验证过，一直显示RELAY
![image](https://github.com/xubiaolin/docker-zerotier-planet/assets/84147842/8226c0b2-4a63-441d-9abd-0236d398b2c0)

**Comment by xubiaolin** [comment]
moon是官方的moon, 不是私有planet的moon

替换了planet就不能使用moon了，

这个项目的moon和planet只能用其中一个

**Comment by dadastory** [comment]
已经收到。
