### ISSUE TITLE
公网轻量yun搭建成功,本地内网服务都可以访问,唯独路由器openwrt网页拒绝访问

### ISSUE THREAD

**Issue by bulesky89857** [xubiaolin/docker-zerotier-planet#141]
本地有一台ubuntu 主机 docker 安装的zerotier-one客户端,正常穿透可以访问上面的服务,但是路由器openwrt同样装的zerotier-one客户端 ,zerotier服务器网页显示正常分配了ip,但是无法访问openwrt管理网页,显示拒绝访问,不知道为什么,既然是内网穿透不应该和内网一样正常访问吗,而且远程桌面也是正常可以穿透访问的,不知道问题出在哪里.

**Comment by xubiaolin** [comment]
可能是防火墙的问题，openwrt可能没有监听0.0.0.0

**Comment by bulesky89857** [comment]
> 可能是防火墙的问题，openwrt可能没有监听0.0.0.0

我openwrt 地址是192.168.1.1:1000,

**Comment by xubiaolin** [comment]
> > 可能是防火墙的问题，openwrt可能没有监听0.0.0.0
> 
> 我openwrt 地址是192.168.1.1:1000,

可以的话你加tg群或者qq群，补充更多的信息以便排查问题
