### ISSUE TITLE
大佬能不能做个不用docker的项目，我的小鸡装不上docker

### ISSUE THREAD

**Issue by iso-lib** [xubiaolin/docker-zerotier-planet#143]

**Comment by xubiaolin** [comment]
什么小鸡装不上docker&nbsp;


徐镖林
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月16日(星期四) 中午11:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [xubiaolin/docker-zerotier-planet] 大佬能不能做个不用docker的项目，我的小鸡装不上docker (Issue #143)

**Comment by iso-lib** [comment]
> 什么小鸡装不上docker&nbsp; 徐镖林 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年5月16日(星期四) 中午11:59 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [xubiaolin/docker-zerotier-planet] 大佬能不能做个不用docker的项目，我的小鸡装不上docker (Issue #143) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

配置超级无敌低,,,只想用利用它的ipv4,穿透出去了就直连.

**Comment by iso-lib** [comment]
解决了
直接安装官方服务器，自己编译了个planet替换
关闭issue
