### ISSUE TITLE
更新功能报错

### ISSUE THREAD

**Issue by hitushen** [xubiaolin/docker-zerotier-planet#148]
<img width="650" alt="image" src="https://github.com/xubiaolin/docker-zerotier-planet/assets/67617494/b5583a7e-4d69-4d9c-8b05-32c36d76f582">

**Comment by xubiaolin** [comment]
什么系统，什么架构

**Comment by hitushen** [comment]
> 什么系统，什么架构
Linux Ubuntu 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
就是develop.sh，的更新。直接删掉了那个容器，脚本报错了
