### ISSUE TITLE
关于自定义Planet和官方Planet的关系的疑问

### ISSUE THREAD

**Issue by ligolas** [xubiaolin/docker-zerotier-planet#149]
按照文档指导，比较顺利的完成了Planet的搭建，并且通过Mac成功访问到了家里的资源。

然后直接拿起iPhone直接输入了网络Id，居然连接成功了，在成员列表和iOS app中可相互确认，确实是手机连接成功了（当时实在没想起来自己漏了什么步骤），但是发现手机无法访问家中资源。

此时再重新复盘的时候才意识到并没有替换Planet文件到iOS上，这时候回头读文档才意识到必须越狱才能实现替换。

所以，关键问题来了，iOS APP是如何连接成功到的自建的服务器的呢？是自建Planet也使用了官方的某种查找服务（根据network Id）呢？还是其他什么原因？

**Comment by xubiaolin** [comment]
自建的planet本质上也连了官方的planet, 如果你客户端没有替换planet, 那么此时你自建的planet扮演的是controller的身份

**Comment by ligolas** [comment]
非常感谢解答。
