### ISSUE TITLE
单个节点的“Peer address”栏中会显示大量重复的连接信息？

### ISSUE THREAD

**Issue by laozhanga** [xubiaolin/docker-zerotier-planet#15]
![Snipaste_2022-04-17_10-48-03](https://user-images.githubusercontent.com/12824607/163698146-ba25ce24-91c7-414e-bce2-2d79805a4046.png)

**Comment by xubiaolin** [comment]
这个我也不太清楚，有可能同时建立多个链接进行保活，或者是前端的bug

**Comment by xubiaolin** [comment]
请pull最新代码，运行deploy.sh， 执行更新命令
![image](https://user-images.githubusercontent.com/51899048/219261984-983018fa-b65d-466b-9883-c2881c93698a.png)
