### ISSUE TITLE
Dockerhub 被墙问题

### ISSUE THREAD

**Issue by TongZiGang** [xubiaolin/docker-zerotier-planet#151]
请问下，如题，有人遇到过么？我网上搜索了一下大多数的回答都是在说DNS被污染了，这问题是不是需要大佬去处理下呢

**Comment by xubiaolin** [comment]
docker hub被墙了，执行以下命令重试

sudo tee /etc/docker/daemon.json <<EOF
{
  "registry-mirrors": [
“https://docker.mirrors.aster.edu.pl”,
    "https://docker.mirrors.imoyuapp.win"
  ]
}
EOF

sudo systemctl daemon-reload
sudo systemctl restart docker

**Comment by TongZiGang** [comment]
感谢楼上

**Comment by TongZiGang** [comment]
请问下大佬，在没有安装过docker的国内设备中怎么弄
执行命令之后报如下
root@hcss-ecs-768d:~# sudo tee /etc/docker/daemon.json <<EOF
{
"registry-mirrors": [
“https://docker.mirrors.aster.edu.pl”,
"https://docker.mirrors.imoyuapp.win"
]
}
EOF

sudo systemctl daemon-reload
sudo systemctl restart docker
{
"registry-mirrors": [
“https://docker.mirrors.aster.edu.pl”,
"https://docker.mirrors.imoyuapp.win"
]
}
Failed to restart docker.service: Unit docker.service not found.

**Comment by TongZiGang** [comment]
> 请问下大佬，在没有安装过docker的国内设备中怎么弄 执行命令之后报如下 root@hcss-ecs-768d:~# sudo tee /etc/docker/daemon.json <<EOF { "registry-mirrors": [ “https://docker.mirrors.aster.edu.pl”, "https://docker.mirrors.imoyuapp.win" ] } EOF
> 
> sudo systemctl daemon-reload sudo systemctl restart docker { "registry-mirrors": [ “https://docker.mirrors.aster.edu.pl”, "https://docker.mirrors.imoyuapp.win" ] } Failed to restart docker.service: Unit docker.service not found.

去搜的资料，国内的镜像站都被屏蔽了T_T

**Comment by xubiaolin** [comment]
> 请问下大佬，在没有安装过docker的国内设备中怎么弄 执行命令之后报如下 root@hcss-ecs-768d:~# sudo tee /etc/docker/daemon.json <<EOF { "registry-mirrors": [ “https://docker.mirrors.aster.edu.pl”, "https://docker.mirrors.imoyuapp.win" ] } EOF
> 
> sudo systemctl daemon-reload sudo systemctl restart docker { "registry-mirrors": [ “https://docker.mirrors.aster.edu.pl”, "https://docker.mirrors.imoyuapp.win" ] } Failed to restart docker.service: Unit docker.service not found.

装一个docker就行

**Comment by TongZiGang** [comment]
谢谢，小白不太清楚怎么做，我去搜一下怎么安装吧

**Comment by xubiaolin** [comment]
> 谢谢，小白不太清楚怎么做，我去搜一下怎么安装吧

我的文档里面有docker的安装教程

**Comment by TongZiGang** [comment]
首先谢谢大佬解答，如果你说的文档是指[README]中的话，那个安装docker的命令因为被墙了导致无法使用，若是其他地方麻烦贴一下地址，谢谢

**Comment by xubiaolin** [comment]
是的，里面有讲到docker的安装：
```
curl -fsSL https://get.docker.com | bash
```

**Comment by TongZiGang** [comment]
这个命令因为docker被墙的原因导致无法使用，连接不上，我就是因为这个命令无法使用，找了很久没有找到解决办法才上来问的，不过现在我找到解决办法了，我安装了了个宝塔面板，然后通过宝塔面板安装上了

**Comment by TongZiGang** [comment]
在华为云国内的服务器中表现如下
root@hcss-ecs-768d:~# curl -fsSL https://get.docker.com |bash 
curl: (28) Failed to connect to get.docker.com port 443 after 130102 ms: Connection timed out

**Comment by xubiaolin** [comment]
export DOWNLOAD_URL="https://mirrors.tuna.tsinghua.edu.cn/docker-ce"
# 如您使用 curl
curl -fsSL https://get.docker.com/ | sh

**Comment by RanHuang** [comment]
今日（2024-09-11）Docker Hub已被解封~~
