### ISSUE TITLE
管理后台密码忘记，选择重置密码即可

### ISSUE THREAD

**Issue by potus2030** [xubiaolin/docker-zerotier-planet#154]
说明中指示运行脚本然后重置，可是，1是删除旧配置，2 卸载， 3是更新版本， 没有一个像是可以重置密码的啊？ 难道要删除旧的配置？
欢迎使用zerotier-planet脚本，请选择需要执行的操作：
1. 安装
2. 卸载
3. 更新
4. 查看信息
5. 退出

**Comment by xubiaolin** [comment]
使用最新代码，你这个是老版本的代码，所以没有这个功能
