### ISSUE TITLE
docker-compose无法正常使用

### ISSUE THREAD

**Issue by yuchkkicn** [xubiaolin/docker-zerotier-planet#156]
我反复测试了下, docker可以正常部署使用,  但是 docker-compose 部署后, 客户端加入服务端网络后, 在管理界面看不到客户端, 不能正常连接

不知道是什么原因

参考docker-compose文件如下

version: '3'

services:
  myztplanet:
    image: xubiaolin/zerotier-planet:latest
    container_name: ztplanet
    ports:
      - 9994:9994
      - 9994:9994/udp
      - 3443:3443
      - 3000:3000
    environment:
      - IP_ADDR4=[110.242.68.xx]
      - IP_ADDR6=
      - ZT_PORT=9994
      - API_PORT=3443
      - FILE_SERVER_PORT=3000
    volumes:
      - ./data/zerotier/dist:/app/dist
      - ./data/zerotier/ztncui:/app/ztncui
      - ./data/zerotier/one:/var/lib/zerotier-one
      - ./data/zerotier/config:/app/config
    restart: unless-stopped

**Comment by xubiaolin** [comment]
看不到客户端，可能是udp端口没开，或者是planet文件替换不对，建议执行zerotier-cli peersk看看planet数量是否正确
