### ISSUE TITLE
为何不使用 host 网络呢？

### ISSUE THREAD

**Issue by JwietPuj-Drin** [xubiaolin/docker-zerotier-planet#160]
这样在 ztncui 中的 Peer address 就能显示真实客户端地址而非 bridge 内网地址了，还能减少 NAT 。

**Comment by xubiaolin** [comment]
感谢您的建议，可以自行修改，我这个是方便测试和部署，方便看到端口占用

**Comment by DoiiarX** [comment]
> 感谢您的建议，可以自行修改，我这个是方便测试和部署，方便看到端口占用

居然是这个原因。我还以为什么讲究。我得重新部署了。害怕。
