### ISSUE TITLE
配置好服务器后，后台看不到客户端

### ISSUE THREAD

**Issue by heavensea** [xubiaolin/docker-zerotier-planet#169]
后台都配置好了，win客户端加入了network id，但是从管理后台看不到这个客户端的加入申请，无法授权通过，客户端则显示requsting_configration。在powershell下想看看是否加入成功，运行：
zerotier-cli.bat join xxxxxxxxxxxx 却显示
C:\ProgramData\ZeroTier\One\zerotier-one_x64.exe: authtoken.secret not found or readable in C:\ProgramData\ZeroTier\One (try again as root)

现在还有什么处理办法？

**Comment by xubiaolin** [comment]
没有替换planet或者是根服务器没有开放udp端口

**Comment by kratos9394** [comment]
用官方的planet可以连接,自建的telnet 9994端口都ok了完全加入不了网络

**Comment by xubiaolin** [comment]
9994端口udp协议看看是否开放，用nc命令检测

**Comment by kratos9394** [comment]
nc -vuz 127.0.0.1 9824
localhost [127.0.0.1] 9824 (?) open

**Comment by xubiaolin** [comment]
那就是没替换planet, zerotier-cli peers命令看看有几个planet

**Comment by kratos9394** [comment]
![image](https://github.com/user-attachments/assets/3d795685-bdac-4485-8e97-b4d0cc6e9749)
就一个

**Comment by kratos9394** [comment]
nc -vuz 1x.xxx.xxx.xxx 9824
Connection to 1x.xxx.xxx.xxx port 9824 [udp/*] succeeded!

**Comment by xubiaolin** [comment]
我看你上面说的9994端口，现在测的又是9824端口，issue问答太麻烦了，请加qq群或者tg群组。
