### ISSUE TITLE
根据您的教程完成后，为什么连接显示的是leaf，而不是plant？

### ISSUE THREAD

**Issue by zhui22222** [xubiaolin/docker-zerotier-planet#17]
而且经常连不上，但是官方的结点都是秒连的，，在天翼云部署的

**Comment by xubiaolin** [comment]
1. 客户端是否替换了planet
2. 秒连指的是哪个环节的连接
3. 3443和9993端口是否开放
4. 客户端是哪个平台
5. zerotier-cli peers的结果提供一下

**Comment by xubiaolin** [comment]
你好，请尝试使用最新的代码进行部署
