### ISSUE TITLE
windows部署客户端后无法连接服务端

### ISSUE THREAD

**Issue by yibohub** [xubiaolin/docker-zerotier-planet#170]
windows11家庭版
![image](https://github.com/user-attachments/assets/b3539d36-5ea6-40e5-970d-cafbd8200a35)
安装和连接提示成功。但是后台看不到。
![image](https://github.com/user-attachments/assets/2de65a23-9209-443d-8b94-9448be7d9acd)
后台只有一个路由器的客户端，windows的客户端没有显示。

**Comment by xubiaolin** [comment]
udp端口没开
