### ISSUE TITLE
非 docker部署方案

### ISSUE THREAD

**Issue by changeflyhigh** [xubiaolin/docker-zerotier-planet#171]
大神, 官方能否提供非docker 的部署方案呢?

**Comment by xubiaolin** [comment]
非docker方案可以自行参考docker版本的脚本来操作

**Comment by changeflyhigh** [comment]
我的意思是说, 能否使用非docker的方式来启动   zerotier-planet

docker run -d \
        --name ${CONTAINER_NAME} \
        -p ${ZT_PORT}:${ZT_PORT} \
        -p ${ZT_PORT}:${ZT_PORT}/udp \
        -p ${API_PORT}:${API_PORT} \
        -p ${FILE_PORT}:${FILE_PORT} \
        -e IP_ADDR4=${ipv4} \
        -e IP_ADDR6=${ipv6} \
        -e ZT_PORT=${ZT_PORT} \
        -e API_PORT=${API_PORT} \
        -e FILE_SERVER_PORT=${FILE_PORT} \
        -v $(pwd)/data/zerotier/dist:/app/dist \
        -v $(pwd)/data/zerotier/ztncui:/app/ztncui \
        -v $(pwd)/data/zerotier/one:/var/lib/zerotier-one -v $(pwd)/data/zerotier/config:/app/config --restart unless-stopped xubiaolin/zerotier-planet:latest

**Comment by xubiaolin** [comment]
能， 你把docker里面的命令直接放到系统里面去执行就行

**Comment by changeflyhigh** [comment]
经测试,  拷贝容器中的脚本到linux上, 也启动不了哦
![图片](https://github.com/user-attachments/assets/48647d82-0867-408b-bbbc-71be28c73a95)

**Comment by xubiaolin** [comment]
建议使用docker的方式进行部署

**Comment by changeflyhigh** [comment]
考虑到docker会添加iptables规则, 强制把端口放行到公网上, 导致端口暴露问题, 所以希望大神还是同步推出非docker部署的版本

**Comment by xubiaolin** [comment]
> 考虑到docker会添加iptables规则, 强制把端口放行到公网上, 导致端口暴露问题, 所以希望大神还是同步推出非docker部署的版本

可以修改脚本，来修改监听的ip地址，监听127.0.0.1即可，这样就没有端口暴露的问题了

**Comment by changeflyhigh** [comment]
> > 考虑到docker会添加iptables规则, 强制把端口放行到公网上, 导致端口暴露问题, 所以希望大神还是同步推出非docker部署的版本
> 
> 可以修改脚本，来修改监听的ip地址，监听127.0.0.1即可，这样就没有端口暴露的问题了

监听127.0.0.1的话, 客户端怎么连接zerotier-planet呢?

**Comment by xubiaolin** [comment]
> > > 考虑到docker会添加iptables规则, 强制把端口放行到公网上, 导致端口暴露问题, 所以希望大神还是同步推出非docker部署的版本
> > 
> > 
> > 可以修改脚本，来修改监听的ip地址，监听127.0.0.1即可，这样就没有端口暴露的问题了
> 
> 监听127.0.0.1的话, 客户端怎么连接zerotier-planet呢?

那你不用docker部署也有一样的问题

**Comment by changeflyhigh** [comment]
> > > > 考虑到docker会添加iptables规则, 强制把端口放行到公网上, 导致端口暴露问题, 所以希望大神还是同步推出非docker部署的版本
> > > 
> > > 
> > > 可以修改脚本，来修改监听的ip地址，监听127.0.0.1即可，这样就没有端口暴露的问题了
> > 
> > 
> > 监听127.0.0.1的话, 客户端怎么连接zerotier-planet呢?
> 
> 那你不用docker部署也有一样的问题

非docker部署的话,  使用systemctl来管理服务, 不会影响iptables规则的呀. 比如 systemctl restart nginx, 跟iptables没有任何关系

**Comment by xubiaolin** [comment]
> > > > > 考虑到docker会添加iptables规则, 强制把端口放行到公网上, 导致端口暴露问题, 所以希望大神还是同步推出非docker部署的版本
> > > > 
> > > > 
> > > > 可以修改脚本，来修改监听的ip地址，监听127.0.0.1即可，这样就没有端口暴露的问题了
> > > 
> > > 
> > > 监听127.0.0.1的话, 客户端怎么连接zerotier-planet呢?
> > 
> > 
> > 那你不用docker部署也有一样的问题
> 
> 非docker部署的话, 使用systemctl来管理服务, 不会影响iptables规则的呀. 比如 systemctl restart nginx, 跟iptables没有任何关系

无法理解你的具体需求，可以的话请添加tg群组或者qq群组交流
