### ISSUE TITLE
关于项目支持配置备份与还原的问题

### ISSUE THREAD

**Issue by SORAPSYGA** [xubiaolin/docker-zerotier-planet#18]
之前使用你的项目搭建成功也能正常使用，最近看到项目代码更新了，请问有没有不重新搭建直接更新最新代码的方法呢

**Comment by SORAPSYGA** [comment]
或者有没有备份配置文件，重新搭建以后通过还原配置文件进行设置还原的方法呢

**Comment by xubiaolin** [comment]
感谢您的建议，更新了代码主要是修复了一些其他平台上部署时出现不能安装的问题。

**Comment by SORAPSYGA** [comment]
> 

非常感谢，现在用得很爽，之前看过好几个类似的搭建PLANET的教程，最后搭下来都是MOON节点，有的是DOCKER项目，但是搭建完成后并没有生成PLANET文件，经过多次的尝试最终发现就只有你这个是可以实现PLANET根服务器的。目前唯一一个问题就是IOS段无法替换PLANET文件导致不能连接上，不过这个无所谓了……

**Comment by emengweb** [comment]
配置文件备份的问题确实很关键，另外，如果可以做成docker-compose部署起来就更方便了 :) 
自己尝试打包了一份，不过配置文件映射不出来，没办法迁移服务，看来还需要等待后续的更新了

**Comment by xubiaolin** [comment]
下载最新代码，执行./deploy.sh， 已经支持了保留配置更新
