### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by Y-pandaman** [xubiaolin/docker-zerotier-planet#2]
您好，我在启动
```docker run -d --name zerotier-planet -p 3443:3443 -p 9993:9993 -p 9993:9993/udp -v /var/lib/zerotier-one:/var/lib/zerotier-one --restart unless-stopped zerotier-planet```
这个命令时，会报错
```docker: Error response from daemon: driver failed programming external connectivity on endpoint zerotier-planet (b0a28ce245f6bbcbb3c2c3a36e99e12235e8883f043db9d6e000ded4c4c06f69): Error starting userland proxy: listen tcp4 0.0.0.0:9993: bind: address already in use.```
使用 netstat -tanlp 查看了端口，显示是zerotier-one在占用9993端口
不知道是不是因为moon节点和planet节点同时布置在云服务器上

**Comment by xubiaolin** [comment]
我修改了文档，请参考新的文档操作。
