### ISSUE TITLE
部署完成之后PLANET 还是会有多个 

### ISSUE THREAD

**Issue by showyoulove1990** [xubiaolin/docker-zerotier-planet#20]
root@hecs-205094:/app# zerotier-cli listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 62f865ae71 50.7.252.138/9993;14111;3895 213 - PLANET
200 listpeers 778cde7190 103.195.103.66/9993;4111;3872 238 - PLANET
200 listpeers cafe04eba9 84.17.53.155/9993;419;3955 156 - PLANET
200 listpeers cafe9efeb9 104.194.8.134/9993;14111;3941 170 - PLANET

<img width="494" alt="image" src="https://user-images.githubusercontent.com/29604166/171840174-2d0c389c-d512-490a-8be2-9ea0ecff18de.png">

**Comment by xubiaolin** [comment]
请检查是否替换了客户端的planet文件

**Comment by showyoulove1990** [comment]
已经替换了 所以有些搞不明白哪里配置的有问题

**Comment by xubiaolin** [comment]
MacOS客户端请尝试重启电脑，然后再执行zerotier-cli peers 看看，本人自测可行

**Comment by xubiaolin** [comment]
@showyoulove1990 请尝试使用最新代码部署

**Comment by showyoulove1990** [comment]
可以了  电脑重启之后 又换了一遍配置文件 现在只剩一个了
