### ISSUE TITLE
自动获取的IPv4地址能否添加IPv6

### ISSUE THREAD

**Issue by zhc637** [xubiaolin/docker-zerotier-planet#23]
自动获取的IP是v4地址嫩否添加IPv6，请教！
我想IPV4+IPV6双地址建立[planet]

**Comment by xubiaolin** [comment]
可以的，后续将持续更新，请关注后续迭代

**Comment by Tilie** [comment]
同样的需求，建立ipv6链接的话，阿里云上可以1000M。

**Comment by xubiaolin** [comment]
你好，请使用最新的代码重新部署，已经支持了ipv6
