### ISSUE TITLE
能否添加对HTTPS的支持

### ISSUE THREAD

**Issue by imwls** [xubiaolin/docker-zerotier-planet#24]
如题，谢谢！

**Comment by xubiaolin** [comment]
是指的控制面板的https支持吗，控制面板可以自行用nginx配置ssl

**Comment by imwls** [comment]
我用docker exec没有找到配置文件

**Comment by xubiaolin** [comment]
这个可以在宿主机上的nginx 配置ssl,转发控制面板的端口即可

**Comment by xubiaolin** [comment]
参考Nginx配置
upstream zerotier {
  server 127.0.0.1: 3443;
}

server {

  listen 443 ssl;

  server_name 你的域名;
  client_max_body_size 1024m;

  # ssl证书地址
  ssl_certificate    pem和或者crt文件的路径;
  ssl_certificate_key key文件的路径;

  # ssl验证相关配置
  ssl_session_timeout  5m;    #缓存有效期
  ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;    #加密算法
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;    #安全链接可选的加密协议
  ssl_prefer_server_ciphers on;   #使用服务器端的首选算法


  location / {
    proxy_pass http: //zerotier;
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen       80;
    server_name  你的域名;
    return 301 https: //$server_name$request_uri;
}

**Comment by xubiaolin** [comment]
不需要，用宿主机的443端口转发3443端口即可，可自行搜索`nginx反向代理`

**Comment by xubiaolin** [comment]
感谢您的建议，后续将继续迭代

**Comment by Da1Liu** [comment]
> 参考Nginx配置
> 
> ```
> upstream zerotier {
>   server 127.0.0.1: 3443;
> }
> 
> server {
> 
>   listen 443 ssl;
> 
>   server_name 你的域名;
>   client_max_body_size 1024m;
> 
>   # ssl证书地址
>   ssl_certificate    pem和或者crt文件的路径;
>   ssl_certificate_key key文件的路径;
> 
>   # ssl验证相关配置
>   ssl_session_timeout  5m;    #缓存有效期
>   ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;    #加密算法
>   ssl_protocols TLSv1 TLSv1.1 TLSv1.2;    #安全链接可选的加密协议
>   ssl_prefer_server_ciphers on;   #使用服务器端的首选算法
> 
> 
>   location / {
>     proxy_pass http: //zerotier;
>     proxy_set_header HOST $host;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }
> }
> 
> server {
>     listen       80;
>     server_name  你的域名;
>     return 301 https: //$server_name$request_uri;
> }
> ```

请问这边没有域名纯IP可配置SSL吗？

**Comment by xubiaolin** [comment]
可以的，但依然还是需要申请证书配置

**Comment by xubiaolin** [comment]
HTTPS建议自行使用NGINX代理
