### ISSUE TITLE
升级能否保留原先的配置

### ISSUE THREAD

**Issue by imwls** [xubiaolin/docker-zerotier-planet#25]
目前发现每次运行./deploy.sh之后，都会删除原先的planet和zerotier配置文件，导致路由和客户端都要重新配置，如果在运行脚本的时候可以选择是否删除原来配置就好了。

**Comment by xubiaolin** [comment]
现在已经支持保留配置升级了
![image](https://user-images.githubusercontent.com/51899048/219262391-70b0c72a-3681-48f2-93c8-12737ffa44c0.png)
