### ISSUE TITLE
关于原zerotier所加入的网络问题

### ISSUE THREAD

**Issue by xingxiuyi** [xubiaolin/docker-zerotier-planet#26]
我看到这个代码中生成了一个新的planet文件，当使用这个文件覆盖客户端配置以后，客户端无法连接原有官方的zerotier节点了。

请问这个是一个bug还是说机制上只允许建立私有网络，而不允许连接官网公共网络？

**Comment by xubiaolin** [comment]
该项目剔除了官方的Planet节点，只允许私有网络
