### ISSUE TITLE
客户端无法连接官方Planet时，好像也无法连接自建Planet

### ISSUE THREAD

**Issue by Zonciu** [xubiaolin/docker-zerotier-planet#27]
客户端无法连接官方Planet时，好像也无法连接自建Planet
同一个地区的两条电信宽带，一个能连接官方Planet，一个不能连接。两个都覆盖planet文件后，只有能正常连接官方Planet的那个网络里的设备可以成功加入自建控制中心。另一个一直都是Requesting Configuration。

**Comment by youtehub** [comment]
是的，不是这个服务器本身的问题，网上有相似的回答，这是客户端所处的网络环境导致的

**Comment by xubiaolin** [comment]
该项目的剔除了官方的planet, 仅仅保留了自建的planet，如果无法连接，请检查端口是否开放，网络是否可达

**Comment by Zonciu** [comment]
发现是服务器9993端口没开，开端口后就连上了。
