### ISSUE TITLE
如果想隔离数据和配置，应该映射容器的哪些路径？

### ISSUE THREAD

**Issue by kkkgo** [xubiaolin/docker-zerotier-planet#29]
我想把数据配置使用单独的卷，以便容器损坏的时候不用重新配置所有客户端，是否可行？

**Comment by kkkgo** [comment]
还有就是build出来的镜像有点大，1.28GB，dockerfile可以考虑下multi-stage builds

**Comment by xubiaolin** [comment]
> 我想把数据配置使用单独的卷，以便容器损坏的时候不用重新配置所有客户端，是否可行？

可以的，映射/var/lib/zerotier-one/ 目录即可

后面有时间我支持一下配置自动备份和导出

**Comment by xubiaolin** [comment]
> 还有就是build出来的镜像有点大，1.28GB，dockerfile可以考虑下multi-stage builds

感谢您的建议，第一版做的比较糙，简单能用就行，后续有空了再继续迭代优化
