### ISSUE TITLE
没有planet文件

### ISSUE THREAD

**Issue by Y-pandaman** [xubiaolin/docker-zerotier-planet#3]
您好，我找不到/opt/zerotier-planet 这个路径，没有planet文件
![image](https://user-images.githubusercontent.com/45302972/142794607-217bd915-2a17-46d7-9068-98ca3c523051.png)

**Comment by xubiaolin** [comment]
请重新按照文档再试试，我这边的启动命令修改了一些。如果还存在问题请详细描述一下你的操作步骤，以便解决问题。

**Comment by Y-pandaman** [comment]
重新启动docker后，有planet文件了，将其复制到windows的指定目录下， 也重启了zerotier，加入了新建的网络，打钩了authorized和active bridge，但是peer status显示离线，用zerotier-cli listpeers也显示服务器是叶节点
![image](https://user-images.githubusercontent.com/45302972/142797725-634bcd49-2dfc-48eb-ae76-0143222db705.png)

![image](https://user-images.githubusercontent.com/45302972/142797742-ac1c4e28-d98f-48ca-8741-b22d94ea53f7.png)

**Comment by xubiaolin** [comment]
显示离线的原因我也不太清楚。我这边plant显示的也是叶子节点。

**Comment by Y-pandaman** [comment]
我在两台电脑上装了，虽然有分配ip，但是相互之间ping不通

**Comment by xubiaolin** [comment]
加下QQ：2205548388，我帮你看下是啥情况， 这样交流方便一些。
