### ISSUE TITLE
卡在这里怎么办

### ISSUE THREAD

**Issue by ppllpig** [xubiaolin/docker-zerotier-planet#30]
使用其他ip请输入要使用的ip,例如1.1.1.1,支持使用域名
使用当前ip请输入:y
-------------------------------------------

----------------------------
当前的ip为:, 是否继续? y/n
y
清除原有内容
rm: cannot remove '/opt/planet': No such file or directory
Error response from daemon: No such container: zerotier-planet
Error: No such container: zerotier-planet
Error: No such image: zerotier-planet
打包镜像
Sending build context to Docker daemon  1.006MB
Step 1/8 : FROM ubuntu:20.04
 ---> bdbe84df0b98
Step 2/8 : ENV TZ=Asia/Shanghai     DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 793be8609160
Step 3/8 : ADD . /app
 ---> Using cache
 ---> 7f0be969e5f9
Step 4/8 : RUN  echo "deb http://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse" > /etc/apt/sources.list     && echo "deb-src http://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse" >> /etc/apt/sources.list     && echo "deb http://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse" >> /etc/apt/sources.list     && echo "deb-src http://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse" >> /etc/apt/sources.list     && echo "deb http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse" >>/etc/apt/sources.list     && echo "deb-src http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse" >>/etc/apt/sources.list     && echo "deb http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse" >>/etc/apt/sources.list     && echo "deb-src http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse" >>/etc/apt/sources.list     && echo "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-security main restricted universe multiverse" >>/etc/apt/sources.list     && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  && echo 'Asia/Shanghai' > /etc/timezone    && apt update && apt install git python3 npm make curl wget -y      && mkdir /usr/include/nlohmann/ && cd /usr/include/nlohmann/ && wget https://github.com/nlohmann/json/releases/download/v3.10.5/json.hpp     && npm config set registry http://registry.npm.taobao.org && npm install -g node-gyp     && apt-get clean && rm -rf /var/lib/apt/lists/*
 ---> Running in 2f31801440d5

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://mirrors.aliyun.com/ubuntu focal InRelease [265 kB]
Get:2 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security InRelease [114 kB]
Ign:3 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/restricted arm64 Packages
Ign:4 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/universe arm64 Packages
Ign:5 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/multiverse arm64 Packages
Ign:6 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/main arm64 Packages
Ign:3 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/restricted arm64 Packages
Ign:4 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/universe arm64 Packages
Ign:5 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/multiverse arm64 Packages
Ign:6 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/main arm64 Packages
Ign:3 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/restricted arm64 Packages
Ign:4 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/universe arm64 Packages
Ign:5 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/multiverse arm64 Packages
Ign:6 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/main arm64 Packages
Ign:3 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/restricted arm64 Packages
Ign:4 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/universe arm64 Packages
Ign:5 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/multiverse arm64 Packages
Ign:6 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/main arm64 Packages
Ign:3 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/restricted arm64 Packages
Ign:4 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/universe arm64 Packages
Ign:5 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/multiverse arm64 Packages
Ign:6 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/main arm64 Packages
Err:3 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/restricted arm64 Packages
  404  Not Found [IP: 101.6.15.130 80]
Ign:4 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/universe arm64 Packages
Ign:5 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/multiverse arm64 Packages
Ign:6 http://mirrors.tuna.tsinghua.edu.cn/ubuntu focal-security/main arm64 Packages
Get:7 http://mirrors.aliyun.com/ubuntu focal-security InRelease [114 kB]
Get:8 http://mirrors.aliyun.com/ubuntu focal-updates InRelease [114 kB]
Get:9 http://mirrors.aliyun.com/ubuntu focal-backports InRelease [108 kB]
Get:10 http://mirrors.aliyun.com/ubuntu focal/restricted Sources [7198 B]
Get:11 http://mirrors.aliyun.com/ubuntu focal/main Sources [1079 kB]
Get:12 http://mirrors.aliyun.com/ubuntu focal/universe Sources [12.3 MB]

**Comment by xubiaolin** [comment]
试试重新部署

**Comment by xubiaolin** [comment]
看起来你没有输入ip地址：

**Comment by xubiaolin** [comment]
```
当前的ip为:, 是否继续? y/n
y
清除原有内容
```
