### ISSUE TITLE
可以更改9993端口吗？

### ISSUE THREAD

**Issue by yajlt** [xubiaolin/docker-zerotier-planet#31]
我这里服务搭建好以后，联通和移动的机器都能联上，电信的联不上。估计是9993端口被电信屏蔽了。有没有什么办法可以把9993端口改成其它的吗？

**Comment by honqiang** [comment]
求解决办法

**Comment by ppllpig** [comment]
https://techoverflow.net/2022/09/27/how-i-fixed-zerotier-one-fatal-error-cannot-bind-to-local-control-interface-port-9993/

**Comment by xubiaolin** [comment]
最新脚本已经支持了指定端口，请使用最新代码重新部署
