### ISSUE TITLE
提示没有zerotier-planet这个镜像

### ISSUE THREAD

**Issue by Gouryella** [xubiaolin/docker-zerotier-planet#33]
安装时提示没有zerotier-planet这个镜像

**Comment by xubiaolin** [comment]
拉一下代码，然后重新执行一下试试

**Comment by ErixWong** [comment]
Error response from daemon: pull access denied for zerotier-planet, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

官方这个镜像是不是没了？

**Comment by xubiaolin** [comment]
请尝试获取最新脚本，然后重新部署
