### ISSUE TITLE
安装过程报错

### ISSUE THREAD

**Issue by Da1Liu** [xubiaolin/docker-zerotier-planet#34]
Cloning into 'ztncui'...
fatal: unable to access 'http://gh-proxy.markxu.vip/https://github.com/key-networks/ztncui.git/': Failed to connect to gh-proxy.markxu.vip port 80: Connection timed out

**Comment by Da1Liu** [comment]
腾讯云服务器

**Comment by xubiaolin** [comment]
把 http://gh-proxy.markxu.vip/https://github.com/key-networks/ztncui.git/ 改成https://github.com/key-networks/ztncui.git就行了

**Comment by Da1Liu** [comment]
请问这个是在哪里改？我在deploy.sh中没找着

**Comment by Da1Liu** [comment]
Linux VM-4-3-centos 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Da1Liu** [comment]
非常感谢谢谢装好了，也只有一个planet。但是有个陌生的节点出现在我的peers列表里面，去查了地址是美国谷歌云的，控制台却看不见，把节点从peers.d文件夹里删了还是会自动出现。用官版的也遇到过这种情况。请问您那边有这样的情况吗？

**Comment by Da1Liu** [comment]
如图

**Comment by Da1Liu** [comment]
cafe9efeb9  104.194.8.134/9993这个节点

**Comment by xubiaolin** [comment]
没有授权这个节点的话，问题不大，我这边是没有这种情况的，可以尝试重新部署来解决这个问题
