### ISSUE TITLE
提示没有zerotier-planet:latest镜像

### ISSUE THREAD

**Issue by Sherdrom** [xubiaolin/docker-zerotier-planet#35]
启动服务
Unable to find image 'zerotier-planet:latest' locally
docker: Error response from daemon: pull access denied for zerotier-planet, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
Error: No such container:path: zerotier-planet:/app/bin/planet

**Comment by xubiaolin** [comment]
试试重新部署

**Comment by Sherdrom** [comment]
> 
问题解决了，居然是因为github连接不上导致的问题
