### ISSUE TITLE
甲骨云安装后，客户端无法加入

### ISSUE THREAD

**Issue by pd-97** [xubiaolin/docker-zerotier-planet#37]
使用甲骨云免费服务器部署，部署完成后，客户端连接网络，然后去控制台看，成员为0，部署几次+换了服务器也是这样，请问我怎么排查问题

**Comment by xubiaolin** [comment]
客户端连接时是否正常返回，客户端能否成功执行`tenet ip 9993 `

**Comment by pd-97** [comment]
客户端连接时 join OK ,telnet 9993正常

**Comment by xubiaolin** [comment]
是否替换了客户端的planet文件？

**Comment by pd-97** [comment]
替换并且重启了zerotier服务

**Comment by xubiaolin** [comment]
请尝试重新部署，如果问题继续存在，请提issue
