### ISSUE TITLE
部署成功  join ok 但是连接失败 提示 REQUESTING_CONFIGURATION

### ISSUE THREAD

**Issue by guider** [xubiaolin/docker-zerotier-planet#39]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/15050634/197515180-7256ba6d-466b-4d6e-848c-b9641cfc58ff.png">

**Comment by guider** [comment]
<img width="530" alt="image" src="https://user-images.githubusercontent.com/15050634/197515248-f3cb8686-6559-48ad-9c50-1873f02e05b4.png">

**Comment by guider** [comment]
planet 已更换

**Comment by xubiaolin** [comment]
重启一下电脑试试

**Comment by FliesQQ** [comment]
之前搭建的没问题，最近搭建的就像po主说的这种情况，只有建服务器那台机子能加入网络，其他的机器都加不进去。国内国外都不行。

**Comment by 1312564541** [comment]
> <img alt="image" width="343" src="https://user-images.githubusercontent.com/15050634/197515180-7256ba6d-466b-4d6e-848c-b9641cfc58ff.png">

跟你一样的问题，客户端状态为REQUESTING_CONFIGURATION，服务器端没有收到入网申请

**Comment by 1312564541** [comment]
> > > <img alt="image" width="343" src="https://user-images.githubusercontent.com/15050634/197515180-7256ba6d-466b-4d6e-848c-b9641cfc58ff.png">
> > 
> > 
> > 跟你一样的问题，客户端状态为REQUESTING_CONFIGURATION，服务器端没有收到入网申请
> 
> 服务器那边换个9993外的端口就好，已经确定是9993被绝大部分国内云服务器商封了。

请问服务器端怎么改

**Comment by xubiaolin** [comment]
最新脚本已经支持了指定端口，请使用最新代码重新部署

**Comment by guider** [comment]
牛逼 666

**Comment by WaterApple09** [comment]
目前看来不是云服务商，而是宽带运营商封了9993的出站方向，用腾讯云和阿里云两台机器互相连没问题
