### ISSUE TITLE
请问：搭建完成后，搭建的Planet显示为LEFT节点

### ISSUE THREAD

**Issue by r6c** [xubiaolin/docker-zerotier-planet#4]
![image](https://user-images.githubusercontent.com/45527749/144181956-1ddf86fb-e003-45ab-ba89-2829e2700c33.png)

看显示使用的还是官方的planet节点。要是在国内某些网络情况不好的地区使用。在无法连接官方的planet节点的情况下，能正常使用吗？

**Comment by xubiaolin** [comment]
我这边显示的和你那边差不多。如果网络情况不好，可以替换客户端的planet文件。

**Comment by r6c** [comment]
客户端的planet文件 就是用的 docker 里的planet文件。 需要替换成什么?

**Comment by xubiaolin** [comment]
只需要把docker里面的planet的文件替换到客户端就行了，看你的描述应该就没什么问题了。具体可以参考https://github.com/xubiaolin/docker-zerotier-planet#%E5%8F%AF%E9%80%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E9%85%8D%E7%BD%AE

**Comment by r6c** [comment]
是的，替换之后是这样显示的。我的意思是在网络不好的情况下，你说替换客户端的planet文件。可是替换之后planet也是官方的planet。在这种情况下，要是官方planet不通，应该也无法建立连接吧？

**Comment by xubiaolin** [comment]
planet文件里面把你服务器的ip写进去了，连接的时候会通过你服务器的ip来连接。
理论上官方的planet不通也是可以连接上的。

问题主要是执行zerotier-cli peers的时候会把你的服务器显示成leaf节点，这个问题我抽空再看看。

**Comment by r6c** [comment]
好的 麻烦了
