### ISSUE TITLE
m1的mac 连接不上，intel的mac却可以

### ISSUE THREAD

**Issue by io-better** [xubiaolin/docker-zerotier-planet#40]

**Comment by io-better** [comment]
系统版本： big sur 11.7.1, 一直提示REQUESTING_CONFIGURATION

**Comment by xubiaolin** [comment]
操作上有什么不一样吗，planet文件替换了吗

**Comment by xubiaolin** [comment]
亲测，x86 mac和m1 mac都没问题

**Comment by zzswang** [comment]
> 系统版本： big sur 11.7.1, 一直提示REQUESTING_CONFIGURATION

兄弟有后续么

**Comment by xubiaolin** [comment]
请使用最新代码，重新部署试试
