### ISSUE TITLE
半小时了，安装100K/S,国内BGP-nat

### ISSUE THREAD

**Issue by ppllpig** [xubiaolin/docker-zerotier-planet#42]
Get:168 http://mirrors.aliyun.com/ubuntu focal/main amd64 liburi-perl all 1.76-2 [77.5 kB]
Get:169 http://mirrors.aliyun.com/ubuntu focal/main amd64 libfile-desktopentry-perl all 0.22-1 [18.2 kB]
Get:170 http://mirrors.aliyun.com/ubuntu focal/main amd64 libfile-fcntllock-perl amd64 0.22-3build4 [33.1 kB]
Get:171 http://mirrors.aliyun.com/ubuntu focal/main amd64 libtimedate-perl all 2.3200-1 [34.0 kB]
Get:172 http://mirrors.aliyun.com/ubuntu focal/main amd64 libhttp-date-perl all 6.05-1 [9920 B]
Get:173 http://mirrors.aliyun.com/ubuntu focal/main amd64 libfile-listing-perl all 6.04-1 [9774 B]
Get:174 http://mirrors.aliyun.com/ubuntu focal/main amd64 libfile-mimeinfo-perl all 0.29-1 [41.5 kB]
Get:175 http://mirrors.aliyun.com/ubuntu focal/main amd64 libfont-afm-perl all 1.20-2 [13.2 kB]
Get:176 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 libfreetype6 amd64 2.10.1-2ubuntu0.2 [341 kB]
Get:177 http://mirrors.aliyun.com/ubuntu focal/main amd64 libfontconfig1 amd64 2.13.1-2ubuntu3 [114 kB]
Get:178 http://mirrors.aliyun.com/ubuntu focal/main amd64 libfontenc1 amd64 1:1.1.4-0ubuntu1 [14.0 kB]
Get:179 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 libglapi-mesa amd64 21.2.6-0ubuntu0.1~20.04.2 [27.4 kB]
Get:180 http://mirrors.aliyun.com/ubuntu focal-security/main amd64 libllvm12 amd64 1:12.0.0-3ubuntu1~20.04.5 [18.8 MB]

**Comment by honqiang** [comment]
没事，我这安装了1个小时
