### ISSUE TITLE
Multiple duplicate entries under the Peer address in the webui

### ISSUE THREAD

**Issue by MANKUD** [xubiaolin/docker-zerotier-planet#44]
Hello,

I want to use an older version of zerotier as this will install the latest version of zerotier and there is a bug which shows multiple duplicate entries under the Peer address in the webui.

**Comment by MANKUD** [comment]
![image](https://user-images.githubusercontent.com/83474708/207274970-6b332987-e475-4219-8f1b-4e03946e5ab9.png)

**Comment by Iam66666** [comment]
I have this problem too, which version you want to use? I will try it later

**Comment by xubiaolin** [comment]
I have this problem too. 
which version you want to use, I will try it later

**Comment by MANKUD** [comment]
I am using version 1.6.5 and it works perfectly fine there are no duplicates. You can try the same one please.

**Comment by MANKUD** [comment]
@xubiaolin did you get a chance to look at it

**Comment by MANKUD** [comment]
@xubiaolin any updates on this  request :(

**Comment by ghbhaha** [comment]
1.Enter container
2.wget https://download.zerotier.com/RELEASES/1.8.1/dist/debian/bullseye/zerotier-one_1.8.1_amd64.deb(Select the desired version.)
3.dpkg -i zerotier-one_1.8.1_amd64.deb
4.Restart container

**Comment by xubiaolin** [comment]
please pull latest code, and run `./deploy.sh`, chose `update` function，and this problem will be resolved.
![image](https://user-images.githubusercontent.com/51899048/219262336-364e88c1-929a-4926-b3ef-a316bbf2ef04.png)

**Comment by MANKUD** [comment]
The problem is still not resolved unfortunately.

![image](https://user-images.githubusercontent.com/83474708/220036099-03fcb90b-092c-461e-a516-b2997250e191.png)

**Comment by xubiaolin** [comment]
> The problem is still not resolved unfortunately.
> 
> ![image](https://user-images.githubusercontent.com/83474708/220036099-03fcb90b-092c-461e-a516-b2997250e191.png)

please pull latest code , and `./deploy.sh`, chose `2 - 更新 ` to update, 
after update, this problem will be resolved.

**Comment by MANKUD** [comment]
![image](https://user-images.githubusercontent.com/83474708/220039483-6d04345e-b42a-4d5f-9427-c212453341b5.png)

**Comment by xubiaolin** [comment]
Are the ports the same?

**Comment by MANKUD** [comment]
hello the ports are different.

![image](https://user-images.githubusercontent.com/83474708/220041475-a82cc711-9779-4f72-a1e0-d43ad4768041.png)

**Comment by MANKUD** [comment]
> > The problem is still not resolved unfortunately.
> > ![image](https://user-images.githubusercontent.com/83474708/220036099-03fcb90b-092c-461e-a516-b2997250e191.png)
> 
> please pull latest code , and `./deploy.sh`, chose `2 - 更新 ` to update, after update, this problem will be resolved.

I tried this and it did not help and its still the same.

**Comment by xubiaolin** [comment]
This should be normal, not a bug.
Multiple ports are used to ensure connectivity

**Comment by xubiaolin** [comment]
Previously, multiple ports were duplicated. After update, it was fixed.

**Comment by MANKUD** [comment]
oh I see so this is normal you mean but on the older version only one port was displayed I think only the port being used currently was displayed? 

![image](https://user-images.githubusercontent.com/83474708/220042252-a9f8cf2a-cc6c-4ce2-9c5f-3f405e070535.png)

**Comment by MANKUD** [comment]
![image](https://user-images.githubusercontent.com/83474708/220042852-fa643452-4d87-4343-9c1e-9b4846b26a8b.png)

**Comment by MANKUD** [comment]
> hello the ports are different.
> 
> ![image](https://user-images.githubusercontent.com/83474708/220041475-a82cc711-9779-4f72-a1e0-d43ad4768041.png)

hello @xubiaolin btw  you can see duplicate ports here too.

**Comment by MANKUD** [comment]
looks like its the same as before and its not fixed.

**Comment by xubiaolin** [comment]
> ![image](https://user-images.githubusercontent.com/83474708/220042852-fa643452-4d87-4343-9c1e-9b4846b26a8b.png)

this version is too old, may be you can try update it.

**Comment by xubiaolin** [comment]
The client will have multiple ports to communicate with the server, so it is normal for you to see multiple ports, but it is not normal to have duplicate ports.

**Comment by MANKUD** [comment]
> > ![image](https://user-images.githubusercontent.com/83474708/220042852-fa643452-4d87-4343-9c1e-9b4846b26a8b.png)
> 
> this version is too old, may be you can try update it.

I mean to say everything is fine on this version only one port displayed and no duplicate ports but one the latest version its not fine

**Comment by xubiaolin** [comment]
> > > ![image](https://user-images.githubusercontent.com/83474708/220042852-fa643452-4d87-4343-9c1e-9b4846b26a8b.png)
> > 
> > 
> > this version is too old, may be you can try update it.
> 
> I mean to say everything is fine on this version only one port displayed and no duplicate ports but on the latest version its not fine

I see, but I'm not sure about the problem. Maybe the official service has been upgraded.

**Comment by MANKUD** [comment]
could you help me on how to downgrade the zerotier version that would be really great.

**Comment by xubiaolin** [comment]
I will support this feature in future updates, please be patient

**Comment by MANKUD** [comment]
ok fine I will wait thank you.
