### ISSUE TITLE
添加了新路由，但没有生效

### ISSUE THREAD

**Issue by gotoin** [xubiaolin/docker-zerotier-planet#46]
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/15847842/208245324-80c74121-b946-44fd-b7a2-d3cff8d95121.png">
<img width="477" alt="image" src="https://user-images.githubusercontent.com/15847842/208245345-d9ca7dd2-c550-4c3a-a0a0-933671f4f952.png">

**Comment by xubiaolin** [comment]
这块目前没有仔细测试，估计是云服务器53端口被禁用了
