### ISSUE TITLE
请问，zerotier-planet或者moon布置能否在域名上进行

### ISSUE THREAD

**Issue by oldskooler** [xubiaolin/docker-zerotier-planet#47]
腾讯或者阿里云的服务器，第二年起就变的很贵；家里宽带有公网ip地址，但是ip地址不固定，几天会变一次，已经使用域名绑定，家里有nas服务器，常年开机的，现在想请问下能否在家里服务器中部署[zerotier-planet]，方便各种设备组成局域网

**Comment by xubiaolin** [comment]
可以在域名上进行的

**Comment by maxin-cn** [comment]
> 可以在域名上进行的

那应该怎么设置呢？比如moon，直接把moon.json中的ipv4地址更改为域名吗？

**Comment by xubiaolin** [comment]
使用最新的代码重新部署一下就行

**Comment by maxin-cn** [comment]
> 使用最新的代码重新部署一下就行
代码获取的也是当前的ip地址，ip变了呢？又重新部署吗？

**Comment by maxin-cn** [comment]
> 使用最新的代码重新部署一下就行

代码获取的也是当前的ip地址，ip变了呢？又重新部署吗？

**Comment by xubiaolin** [comment]
最新的代码会提示你，可以使用域名来替代ip

**Comment by maxin-cn** [comment]
> 最新的代码会提示你，可以使用域名来替代ip

您代码里面似乎是把moon中ipv4地址给更换成了域名，但似乎zerotier目前并不支持用ddns来搭建moon服务器？您说的是指可以使用ddns来访问控制界面吗？

**Comment by xubiaolin** [comment]
ddns需要你自己做，目前只是支持通过域名来替换ipv4

**Comment by oldskooler** [comment]
域名需要什么格式的？ xxx1.xxx.xxx 还是 xxx.xxx

**Comment by oldskooler** [comment]
大佬又来更新了啊，能测试下是否支持ipv4 域名吗

**Comment by xubiaolin** [comment]
亲测，域名目前有些问题，原因不太清楚

**Comment by wzqvip** [comment]
同求。我是家宽，有动态公网ip，群晖用域名ddns效果很好，大概2-3天会变一次ip。

**Comment by Shiradan** [comment]
我也是同样的问题，很想用域名，但我查了下，看到国外论坛有人说过zerotier底层实现不支持DNS，更别说DDNS了，全部是基于IP地址的连接访问，因此域名服务也就不可用，目前只能每次IP变更重新部署一遍，并且每个客户端重新覆盖一遍planet，有需要的可以准备一套备用的内网穿透服务作为重新部署的跳板，机子不多也就每次花个半小时左右的功夫，勉强可以接受。zerotier胜在无门槛，tailscale一系过于麻烦了，自己配要折腾很长时间，我懒了。感谢作者的docker镜像，对比了几款同源的，算是最简单好用的了。

**Comment by simplove** [comment]
测试了下，域名确实不行，牙根没看有向服务器的端口请求，应该是还没有到DNS那一步

**Comment by simplove** [comment]
https://github.com/zerotier/zeronsd
需要配合这个来使用，未来在2.0上面可以直接实现DNS的功能 等大佬研究下怎么弄@xubiaolin

**Comment by Gxyloj** [comment]
部署时ipv4直接输域名，其他设备加入网络控制台看不到用户

**Comment by xubiaolin** [comment]
暂不支持域名

**Comment by ys1231** [comment]
`#!/bin/bash

#use /bin/bash /volume1/docker/zerotier/updateip.sh

ipfile="/volume1/docker/zerotier/ip.txt"
jsonfile="/volume1/docker/zerotier/moon.json"

# debug
#ipfile="./ip.txt"
#jsonfile="moon.json"

url="http://4.ipw.cn"

if [ -e "$ipfile" ]; then
    ip=$(cat "$ipfile")
    echo "oldip $ip"
else
    /bin/touch "$ipfile"
    echo "touch $ipfile"
    echo "0.0.0.0" > "$ip"
fi

oldip=$(cat "$ipfile")

newip=$(curl -s "$url")


if [ "$oldip" = "$newip" ]; then
    echo "no need update ip for json"
else
    echo "need change json restart docker"
    echo "$newip" > "$ipfile"
    new_stable_endpoints='   "stableEndpoints": ["'$newip'/9993"]'
    echo "new ip $newip"
    sed -i '7s|.*|'"$new_stable_endpoints"'|' "$jsonfile"
    echo "update json"
    docker restart zerotier-moon
    echo "restart docker"
fi
`

通过这种方式把脚本保存到  /volume1/docker/zerotier/updateip.sh 
添加定时任务每分钟 执行一次

**Comment by zeroworld1** [comment]
现在只会动态域名方式了吗？还是zerotier底层就需要固定IP？
