### ISSUE TITLE
云服务器 Ubuntu dockers 没有/opt/文件，无法下载planet

### ISSUE THREAD

**Issue by planet618** [xubiaolin/docker-zerotier-planet#49]
请问大家，我的云服务器是ubuntu20.04系统包含dockers，登陆名是不是必须改名opt（不然我的目录下没有/opt/这个文件夹，也找不到planet文件）
已经重复多次，都不行。

**Comment by xubiaolin** [comment]
请拉取最新的代码重新部署一下，最新的代码修改目录到/tmp/目录下了

**Comment by planet618** [comment]
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/80933595/218952348-c9c26a1f-3553-414b-b052-d51b38884d03.png">

**Comment by planet618** [comment]
你好，卡在上面这页了

**Comment by xubiaolin** [comment]
国内网络的问题，多试试看

**Comment by planet618** [comment]
好的，但是我想请问一下，为什么我找不到您指定的目录文件夹，但是我把用户名改成对应文件夹名的时候就可以产生这个planet文件，（但是腾讯云服务器目前不能用其他用户名登陆了，我很苦恼。）例如我目前的名字只能使用lighthouse或者ubuntu这俩名字登录，因为不能改成tmp，所以在目录里找不到tmp文件夹，也就没有planet。

**Comment by planet618** [comment]
我这几次都能把它安装成功，但是就是没有planer文件，不知道什么问题，所以我不断地重装系统，再次安装，尝试改名（腾讯云目前不能改名了，也不知道为什么，只能用lighthouse或者Ubuntu名字登录）。昨天的时候我看可以改名，我就改成opt或者其他教程里指定的文件夹名字，都产生了planet文件，但是偏偏网址都打不开，所以又开始重装系统。

**Comment by xubiaolin** [comment]
你应该不是root账号运行的，所以没有权限写入/opt目录。
你使用最新的代码来运行，最新的代码把文件写到/tmp目录下了

你直接执行命令`cd /tmp`就能看到了，/tmp目录是所有人都能看到的

**Comment by planet618** [comment]
好的
谢谢，学习了

**Comment by planet618** [comment]
感谢，问题已解决，虽然安装了大概40分钟以上，但是终于成功安装了，另外，我的ping延迟大概120左右正常吗

**Comment by xubiaolin** [comment]
用几天观察下看看，如果是国内的机器，ping的延迟一般会在几十，或者个位数

**Comment by planet618** [comment]
好的，谢谢

**Comment by planet618** [comment]
请问我配置好的话，用来传输视频高清视频稳定吗，我用来装无人机上传输的

**Comment by planet618** [comment]
用udp转发

**Comment by xubiaolin** [comment]
如果走直连p2p的话就很快，走中继模式的话就看你中继服务器的带宽了

**Comment by xubiaolin** [comment]
不需要，zerotier会自动尝试p2p，具体成功率根据你的网络NAT情况来看

**Comment by xubiaolin** [comment]
可以执行命令 zerotier-cli peers, 如果是DIRECT就表示直连，RELAY就表示中继

**Comment by planet618** [comment]
好滴，另外请问下，重启服务器这些，需要重启zerotier服务吗

**Comment by xubiaolin** [comment]
不需要，会自动启动

**Comment by planet618** [comment]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/80933595/218981133-76bc0458-233f-433c-9c1e-e762d1641747.png">

**Comment by planet618** [comment]
我没看错的话，应该是direct，但是延迟仍然较高，并且我手机接入网络了，但是显示是reley，是因为没有配置planet吗

**Comment by xubiaolin** [comment]
需要替换planet，才能达到最好的效果

**Comment by planet618** [comment]
请问下，我的linux ubuntu系统精简版里面，加入网络的指令好像不行可能是什么原因？

他的报错：bash: zerotier-cli: command not found

**Comment by xubiaolin** [comment]
```
cd /var/lib/zerotier-one 
./zerotier-cli
```

**Comment by planet618** [comment]
你好，linux客户端安装好zerotier后，好像处于运行中导致我删除不了planet问价或者也替换不了，请问这种有什么办法解决吗

**Comment by xubiaolin** [comment]
就算是运行中也能删除的，看看是不是权限不够，用管理员权限试试

**Comment by planet618** [comment]
搞定，谢谢.
