### ISSUE TITLE
只有动态公网IP可以用这个吗？

### ISSUE THREAD

**Issue by JupiterDust01** [xubiaolin/docker-zerotier-planet#5]
只有动态公网IP可以用这个吗？

**Comment by xubiaolin** [comment]
没试过，你可以试试把ip换成你的动态域名，看看能不能行。

**Comment by xubiaolin** [comment]
然后还得做端口映射，估计挺麻烦

**Comment by JupiterDust01** [comment]
感谢您的回复，动态域名和端口映射我都做了，但是没有成功。




在2021年12月23日 ***@***.***> 写道：

然后还得做端口映射，估计挺麻烦

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
