### ISSUE TITLE
安装过程报错

### ISSUE THREAD

**Issue by ahl20** [xubiaolin/docker-zerotier-planet#52]
您好，
非常感谢提供便捷的脚本安装，但是安装过程中报错，能看一下是怎么回事吗？看了一下之前的issue，感觉也是那个链接的问题？
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/34300071/219332632-45a89c37-8ea5-4533-b214-57e005542a9a.png">
我的安装环境是腾讯云，ubuntu18.04

**Comment by xubiaolin** [comment]
网络问题，请多重试几次

**Comment by ahl20** [comment]
> 网络问题，请多重试几次

好的回复啊，非常感谢，我等下换个网络环境试试！
