### ISSUE TITLE
/tmp目录下没有planet 文件

### ISSUE THREAD

**Issue by xiafengjieying** [xubiaolin/docker-zerotier-planet#57]
您好，我安装成功后，可以打开control 界面，但/tmp目录下没有planet 文件，这个有别的地方可以下载么？

**Comment by xubiaolin** [comment]
请提供一下部署的环境和部署日志，建议使用最新代码部署一下

**Comment by xiafengjieying** [comment]
我是在腾讯云轻服务器上部署，操作系统如下：
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

部署日志，我不太确定如何拿到？

**Comment by xubiaolin** [comment]
我刚开了一台腾讯轻量云和你一样的系统，试了一下，没有问题
你能看到如下字样吗？
![image](https://user-images.githubusercontent.com/51899048/221501157-63fd8fe9-ca48-4572-926c-630ca51b88ad.png)

请尝试以下使用最新代码重新部署

**Comment by xiafengjieying** [comment]
我重新安装了一遍，然后把日志 放到一个文件中，以下是最后部分，以及ls /tmp 的结果，请查收
Removing intermediate container b9a9af011274
 ---> 3595b9d283d2
Step 15/16 : VOLUME [ "/app","/var/lib/zerotier-one" ]
 ---> Running in b0d28d765132
Removing intermediate container b0d28d765132
 ---> 0fd9d5f1a05d
Step 16/16 : CMD /bin/sh -c "cd /var/lib/zerotier-one && ./zerotier-one -p`cat /app/zerotier-one.port` -d; cd /app/ztncui/src;npm start"
 ---> Running in 4970fb9acd81
Removing intermediate container 4970fb9acd81
 ---> 1a41fad227ef
Successfully built 1a41fad227ef
Successfully tagged zerotier-planet:latest
启动服务
fbe90e144800143b301d10a2c77206b14e7f72a90d81040d93eb47b9547d01ad
planet文件路径为 /tmp/planet
planet server端口为: 9993, 请在防火墙放行该端口的tcp和udp协议
enjoy~
-----
root@VM-16-17-ubuntu:/home/ubuntu/docker-zerotier-planet# ll /tmp/pla*
ls: cannot access '/tmp/pla*': No such file or directory

**Comment by xubiaolin** [comment]
你进入容器内部看看，执行`docker exec -it zerotier-planet sh` 看看/app/bin目录下面有没有planet, 有的话拷贝出来就行了

**Comment by xubiaolin** [comment]
首页新增了QQ交流群二维码，可以加入QQ群咨询

**Comment by xiafengjieying** [comment]
进入容器后，这个文件是存在的，但从容器外拷贝，却不成功...
root@VM-16-17-ubuntu:/tmp# docker cp zerotier-planet:/app/bin/planet .
root@VM-16-17-ubuntu:/tmp# ls /tmp/pl*
ls: cannot access '/tmp/pl*': No such file or directory
root@VM-16-17-ubuntu:/tmp# ls /tmp/p*
ls: cannot access '/tmp/p*': No such file or directory

**Comment by xubiaolin** [comment]
我试了以下，命令执行成功，文件也能看到

![image](https://user-images.githubusercontent.com/51899048/221511799-85e75961-ebca-4ae3-8b15-b25cc78ce1fa.png)
