### ISSUE TITLE
您好，脚本能否加入备份功能

### ISSUE THREAD

**Issue by orzonzofz** [xubiaolin/docker-zerotier-planet#59]
我需要组网的设备太多，而且都是固定ip，如果以后迁移或是重装，那可太痛苦了。
或者能否告知备份哪个配置文件？

**Comment by qzwl** [comment]
+1 网上都是如何搭建，但是没有人出如何迁移或者备份的教程。每次重装都要一台一台设置过，如果能继承之前的id就好了。

**Comment by xubiaolin** [comment]
备份功能现在感觉就是很鸡肋，如果planet的ip发生了变化，所有客户机的planet文件都需要重新设置，意义不大。

**Comment by qzwl** [comment]
> 备份功能现在感觉就是很鸡肋，如果planet的ip发生了变化，所有客户机的planet文件都需要重新设置，意义不大。

还是有必要的。 大大出一个呗 或者出个手工备份的教程。

**Comment by xubiaolin** [comment]
> > 备份功能现在感觉就是很鸡肋，如果planet的ip发生了变化，所有客户机的planet文件都需要重新设置，意义不大。
> 
> 还是有必要的。 大大出一个呗 或者出个手工备份的教程。

有必要是肯定的，但是你服务器的ip变了，就必须要重新部署，之前备份的也没用。服务器ip不变的话，自行备份docker的数据就行。

**Comment by qzwl** [comment]
> > > 备份功能现在感觉就是很鸡肋，如果planet的ip发生了变化，所有客户机的planet文件都需要重新设置，意义不大。
> > 
> > 
> > 还是有必要的。 大大出一个呗 或者出个手工备份的教程。
> 
> 有必要是肯定的，但是你服务器的ip变了，就必须要重新部署，之前备份的也没用。服务器ip不变的话，自行备份docker的数据就行。

好的，感谢大大。像我这边ip肯定不变的。但是就怕后续操作失误造成问题。然后又得重新部署。我之前就是操作失误了，造成重新部署。后来找了一圈找到您的这个脚本。有一键部署和更新功能。然后又是docker环境。就是为了以后不想重新捣鼓了。
