### ISSUE TITLE
planet服务器不生效，客户端查看不到该planet

### ISSUE THREAD

**Issue by zkh1992** [xubiaolin/docker-zerotier-planet#6]
下载服务器 /opt/zerotier-planet 下的planet文件并 将planet文件覆盖粘贴到C:\ProgramData\ZeroTier\One中后通过services.msc重启zerotier-one服务后powershell输入zerotier-cli listpeers并没有对应自己服务器ip地址的planet，还是只有官方的
PS C:\Users\35087> zerotier-cli listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 62f865ae71 50.7.252.138/9993;11154;1338 -216 - PLANET
200 listpeers 778cde7190 103.195.103.66/9993;1122;1496 -372 - PLANET
200 listpeers 98b8b6091e - -1 - LEAF
200 listpeers b0273d23e3 - -1 - LEAF
200 listpeers cafe04eba9 84.17.53.155/9993;1052;1052 -522 - PLANET
200 listpeers cafe7b4cdf - -1 - PLANET
200 listpeers f7a68b8ff2 45.32.95.235/62913;152;426 736 1.6.6 LEAF

**Comment by zkh1992** [comment]
我试了一下 docker运行的时候，把外部端口换回-p 9993:9993 -p 9993:9993/udp可以找到我服务器，但是提示是Leaf。下面日志第三个即是我部署planet的服务器
C:\Users\35087>zerotier-cli listpeers
200 listpeers <ztaddr> <path> <latency> <version> <role>
200 listpeers 62f865ae71 50.7.252.138/9993;400;620 -220 - PLANET
200 listpeers 778cde7190 103.195.103.66/9993;5412;856 -456 - PLANET
200 listpeers 789e65f709 **139.186.XX.XX/9993;10802;10802 44 1.8.3 LEAF**
200 listpeers b0273d23e3 - -1 - LEAF
200 listpeers cafe04eba9 84.17.53.155/9993;15552;920 -520 - PLANET
200 listpeers cafe7b4cdf - -1 - PLANET
200 listpeers f7a68b8ff2 45.32.95.235/62913;196;472 228 1.6.6 LEAF

**Comment by zkh1992** [comment]
这个模式下ping了一下延迟几百ms，很明显用的还是官方的planet

**Comment by xubiaolin** [comment]
这里可能有些小问题，我抽空看看

**Comment by blacklad** [comment]
+1

**Comment by gorquan** [comment]
有什么思路不，我比较感兴趣研究一下

**Comment by xubiaolin** [comment]
该问题已修复，请大家按照文档重新尝试 @gorquan @blacklad @zkh1992
