### ISSUE TITLE
linux端如何退出已加入的网络（指令）

### ISSUE THREAD

**Issue by planet618** [xubiaolin/docker-zerotier-planet#60]
因为需要调整网络，需要将已经加入该网络的linux端退出网络，windows和手机因为可以打开app，程序，方便忘记网络（退出网络），
但是网上找了一圈，没找到linux端退出已加入网络的指令

**Comment by A-U-OK** [comment]
zerotier-cli leave ************  星号是你要退出的网络id

**Comment by qzwl** [comment]
zerotier-cli orbit <moon id> <moon id>    加入Moon节点
zerotier-cli deorbit  <moon id>    离开Moon节点
zerotier-cli join <局域网id>   加入局域网
zerotier-cli leave <局域网id>   离开局域网
zerotier-cli listpeers     查看连接情况
killall -9 zerotier-one      杀死进程，得多用几次才能完全杀死，
直至系统连续提示“zerotier-one: no process found.

我收集的几个命令。希望能帮助你。 这些命令Windows、MAC、Linux平台都通用的
