### ISSUE TITLE
几个端口问题

### ISSUE THREAD

**Issue by underlaw** [xubiaolin/docker-zerotier-planet#62]
（需要开放 3443/tcp 端口，9993/tcp 端口，9993/udp 端口）

planet server端口为: 9994, 请在防火墙放行该端口的tcp和udp协议

![image](https://user-images.githubusercontent.com/33020405/230817557-c9f6ce9d-b554-4d67-a28e-7e9e3d986b3e.png)

文档说明里 要开放3443，这是端口是面板的吗？
9993开放tcp udp,是服务端口？和文档的9994是同理？

**Comment by xubiaolin** [comment]
3443是面板的，9993是默认的端口，如果你改成了9994，就要开放9994端口
