### ISSUE TITLE
能否更新到新版本的zerotier

### ISSUE THREAD

**Issue by qzwl** [xubiaolin/docker-zerotier-planet#66]
能否更新到新版本的zerotier

**Comment by xubiaolin** [comment]
alpine版本的可能是停在了1.8， 后续我改下基础镜像

**Comment by qzwl** [comment]
> alpine版本的可能是停在了1.8， 后续我改下基础镜像

我这边的zerotier 安装后是1.10.2 ，希望更改了以后能通过更新程序直接升级。感谢。

**Comment by d0ng13** [comment]
提供一个参考
[zerotier-docker](https://github.com/zyclonite/zerotier-docker)
可顺利构建1.10.6版本。实际使用感受不到明显差异。

**Comment by xubiaolin** [comment]
最新脚本可以安装最新的zerotier

**Comment by hisune** [comment]
> 最新脚本可以安装最新的zerotier

貌似现在 `deploy.sh` 脚本中的upgrade，也只能执行alpine中的`apk upgrade zerotier-one`，如何升级到最新的zerotier-one版本？
