### ISSUE TITLE
Alpine Linux最新的3.18版本软件源没有zerotier-one包

### ISSUE THREAD

**Issue by IazgnoT** [xubiaolin/docker-zerotier-planet#67]
Alpine Linux最新的3.18版本软件源没有zerotier-one包，停留在3.17了，不知道后续会不会更新。
安装脚本里用的是latest版本，会造成无法安装，手动修改成alpine:3.17后正常安装。

![image](https://github.com/xubiaolin/docker-zerotier-planet/assets/46050929/94e12381-a7a3-4007-b65b-88e94da4073a)

![image](https://github.com/xubiaolin/docker-zerotier-planet/assets/46050929/c024352f-d949-4a3b-9b0a-054c9f2f2e85)

**Comment by xubiaolin** [comment]
是的，前面也有反馈说升级失败的，其实就是因为alpine版本停止更新了，后续修改一下基础镜像为ubuntu, 这样就能更新到最新版本了

**Comment by IazgnoT** [comment]
> 是的，前面也有反馈说升级失败的，其实就是因为alpine版本停止更新了，后续修改一下基础镜像为ubuntu, 这样就能更新到最新版本了

好的，那我关闭issue了
