### ISSUE TITLE
安装过程中报错了，permission denied

### ISSUE THREAD

**Issue by planet618** [xubiaolin/docker-zerotier-planet#69]
<img width="1273" alt="image" src="https://github.com/xubiaolin/docker-zerotier-planet/assets/80933595/0bb359a4-fb9e-4e58-a034-4733c2e344c0">

**Comment by planet618** [comment]
<img width="1270" alt="image" src="https://github.com/xubiaolin/docker-zerotier-planet/assets/80933595/8dacdbc3-37b0-4b8f-8ce1-d26c545fcaf7">

**Comment by llity** [comment]
怎么解决的呢？谢谢

**Comment by xubiaolin** [comment]
> 怎么解决的呢？谢谢

用root身份执行，这个是权限不足

**Comment by llity** [comment]
@xubiaolin  谢谢，docker也在root下安装吗？我用root似乎安装存在点问题

**Comment by xubiaolin** [comment]
> @xubiaolin 谢谢，docker也在root下安装吗？我用root似乎安装存在点问题

docker也在root账户下安装，安装docker使用命令： curl -fsSL https://get.docker.com | bash

**Comment by llity** [comment]
我用root安装这样的错误
`
![image](https://github.com/xubiaolin/docker-zerotier-planet/assets/11771112/847bdfb0-8a9b-4837-bd61-40da1bc072fe)
`

**Comment by xubiaolin** [comment]
这个错误可以忽略，不用管他

**Comment by llity** [comment]
> 这个错误可以忽略，不用管他

感谢，可以了
