### ISSUE TITLE
最新代码重新部署时卡住

### ISSUE THREAD

**Issue by wekingchen** [xubiaolin/docker-zerotier-planet#70]
用最新代码在HK服务器上部署时，卡在这一步了
![image](https://github.com/xubiaolin/docker-zerotier-planet/assets/22815621/720b72fd-6455-4f58-b630-49c40ced1abc)

**Comment by xubiaolin** [comment]
可以尝试中断，然后重新部署

**Comment by xubiaolin** [comment]
可以尝试中断，然后重新部署

**Comment by wekingchen** [comment]
试过了，还是卡住，可能是这个教育网点海外访问不到

**Comment by xubiaolin** [comment]
这个是专门针对国内优化的，海外的话得把代码里面的加速地址去掉，后续我优化一版没有加速的。

**Comment by wekingchen** [comment]
好的，具体应该去哪一行代码呢？

**Comment by xubiaolin** [comment]
如果你能看懂代码的话，看下代码就知道了，如果不懂代码的话，就等几天，我迭代下
