### ISSUE TITLE
可以自定义planet节点的监听端口号吗？

### ISSUE THREAD

**Issue by lgwylyc** [xubiaolin/docker-zerotier-planet#71]
如题，默认的udp9993特征太明显，很容易被扫描工具发现，谢谢！

**Comment by xubiaolin** [comment]
最新的脚本已经支持了端口自定义，请用最新的脚本重新部署

**Comment by lgwylyc** [comment]
可能说的不对，我是要Zertotier自定义客户端本地监听端口，现在已经可以了。
创建local.conf文件，var/lib/zerotier-one/local.conf
{
 "settings": {
 "primaryPort":9999
 }
}

**Comment by xubiaolin** [comment]
客户端的自己改就行了
