### ISSUE TITLE
arm平台部署时打包失败

### ISSUE THREAD

**Issue by FouRT1900** [xubiaolin/docker-zerotier-planet#72]
wrote 000000224ad07329.moon (signed world with timestamp 1684548595849)
../../node/Utils.cpp:59:10: fatal error: asm/hwcap.h: No such file or directory
   59 | #include <asm/hwcap.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
The command '/bin/sh -c cd /app && git clone --progress https://ghself.markxu.online/https://github.com/zerotier/ZeroTierOne.git --depth 1    && zerotier-one -d && sleep 5s && ps -ef |grep zerotier-one |grep -v grep |awk '{print $1}' |xargs kill -9     && cd /var/lib/zerotier-one && zerotier-idtool initmoon identity.public >moon.json    && cd /app/patch && python3 patch.py     && cd /var/lib/zerotier-one && zerotier-idtool genmoon moon.json && mkdir moons.d && cp ./*.moon ./moons.d     && cd /app/ZeroTierOne/attic/world/ && sh build.sh     && sleep 5s     && cd /app/ZeroTierOne/attic/world/ && ./mkworld     && mkdir /app/bin -p && cp world.bin /app/bin/planet     && TOKEN=$(cat /var/lib/zerotier-one/authtoken.secret)     && echo "ZT_TOKEN=$TOKEN">> /app/ztncui/src/.env' returned a non-zero code: 1
镜像打包失败，请重试

**Comment by xubiaolin** [comment]
最新代码打包可以成功，但是不知道能不能正常使用

**Comment by xubiaolin** [comment]
已取消对arm的支持，后续再考虑
