### ISSUE TITLE
镜像打包失败

### ISSUE THREAD

**Issue by unizhu** [xubiaolin/docker-zerotier-planet#77]
Debian 11 上面安装失败：

ERROR: failed to solve: process "/bin/sh -c sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories     && apk update    && mkdir -p /usr/include/nlohmann/ && cd /usr/include/nlohmann/ && wget https://ghself.markxu.online/https://github.com/nlohmann/json/releases/download/v3.10.5/json.hpp     && apk add --no-cache git python3 npm make g++ zerotier-one linux-headers    && mkdir /app -p &&  cd /app && git clone --progress https://ghself.markxu.online/https://github.com/key-networks/ztncui.git    && cd /app/ztncui/src     && cp /app/patch/binding.gyp .    && echo \"开始配置npm环境\"    && npm install -g --progress --verbose node-gyp --registry=https://registry.npmmirror.com    && npm install  --registry=https://registry.npmmirror.com    && echo 'HTTP_PORT=3443' >.env     && echo 'NODE_ENV=production' >>.env     && echo 'HTTP_ALL_INTERFACES=true' >>.env     && echo \"ZT_ADDR=localhost:${ZT_PORT}\" >>.env    && echo \"${ZT_PORT}\" >/app/zerotier-one.port     && cp -v etc/default.passwd etc/passwd" did not complete successfully: exit code: 1
镜像打包失败，请重试

**Comment by jueinin** [comment]
同样的问题，在下载nodejs的时候，走了官方的节点，下不下来，这玩意儿还很难配代理。得作者改一下吧

#0 24.48 added 126 packages in 7s
#0 24.48 npm verb exit 0
#0 24.49 npm info ok 
#0 163.7 npm ERR! code 1
#0 163.7 npm ERR! path /app/ztncui/src/node_modules/argon2
#0 163.7 npm ERR! command failed
#0 163.7 npm ERR! command sh -c node-gyp rebuild
#0 163.7 npm ERR! gyp info it worked if it ends with ok
#0 163.7 npm ERR! gyp info using node-gyp@9.3.0
#0 163.7 npm ERR! gyp info using node@19.7.0 | linux | x64
#0 163.7 npm ERR! gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
#0 163.7 npm ERR! gyp http GET https://nodejs.org/download/release/v19.7.0/node-v19.7.0-headers.tar.gz
#0 163.7 npm ERR! gyp WARN install got an error, rolling back install
#0 163.7 npm ERR! gyp ERR! configure error 
#0 163.7 npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v19.7.0/node-v19.7.0-headers.tar.gz failed, reason: connect ETIMEDOUT 104.20.22.46:443
#0 163.7 npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/node_modules/minipass-fetch/lib/index.js:130:14)
#0 163.7 npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:512:28)
#0 163.7 npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:496:9)
#0 163.7 npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:524:35)
#0 163.7 npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:151:8)
#0 163.7 npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
#0 163.7 npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
#0 163.7 npm ERR! gyp ERR! System Linux 5.4.0-148-generic
#0 163.7 npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
#0 163.7 npm ERR! gyp ERR! cwd /app/ztncui/src/node_modules/argon2
#0 163.7 npm ERR! gyp ERR! node -v v19.7.0
#0 163.7 npm ERR! gyp ERR! node-gyp -v v9.3.0
#0 163.7 npm ERR! gyp ERR! not ok
#0 163.8 
#0 163.8 npm ERR! A complete log of this run can be found in:
#0 163.8 npm ERR!     /root/.npm/_logs/2023-06-25T08_28_36_931Z-debug-0.log
------
Dockerfile:10
--------------------
   9 |     
  10 | >>> RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories \  11 | >>>     && apk update\
  12 | >>>     && mkdir -p /usr/include/nlohmann/ && cd /usr/include/nlohmann/ && wget https://ghself.markxu.online/https://github.com/nlohmann/json/releases/download/v3.10.5/json.hpp \
  13 | >>>     && apk add --no-cache git python3 npm make g++ zerotier-one linux-headers\
  14 | >>>     && mkdir /app -p &&  cd /app && git clone --progress https://ghself.markxu.online/https://github.com/key-networks/ztncui.git\
  15 | >>>     && cd /app/ztncui/src \
  16 | >>>     && cp /app/patch/binding.gyp .\
  17 | >>>     && echo "开始配置npm环境"\
  18 | >>>     && npm install -g --progress --verbose node-gyp --registry=https://registry.npmmirror.com\
  19 | >>>     && npm install  --registry=https://registry.npmmirror.com\
  20 | >>>     && echo 'HTTP_PORT=3443' >.env \
  21 | >>>     && echo 'NODE_ENV=production' >>.env \
  22 | >>>     && echo 'HTTP_ALL_INTERFACES=true' >>.env \
  23 | >>>     && echo "ZT_ADDR=localhost:${ZT_PORT}" >>.env\
  24 | >>>     && echo "${ZT_PORT}" >/app/zerotier-one.port \
  25 | >>>     && cp -v etc/default.passwd etc/passwd
  26 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories     && apk update    && mkdir -p /usr/include/nlohmann/ && cd /usr/include/nlohmann/ && wget https://ghself.markxu.online/https://github.com/nlohmann/json/releases/download/v3.10.5/json.hpp     && apk add --no-cache git python3 npm make g++ zerotier-one linux-headers    && mkdir /app -p &&  cd /app && git clone --progress https://ghself.markxu.online/https://github.com/key-networks/ztncui.git    && cd /app/ztncui/src     && cp /app/patch/binding.gyp .    && echo \"开始配置npm环境\"    && npm install -g --progress --verbose node-gyp --registry=https://registry.npmmirror.com    && npm install  --registry=https://registry.npmmirror.com    && echo 'HTTP_PORT=3443' >.env     && echo 'NODE_ENV=production' >>.env     && echo 'HTTP_ALL_INTERFACES=true' >>.env     && echo \"ZT_ADDR=localhost:${ZT_PORT}\" >>.env    && echo \"${ZT_PORT}\" >/app/zerotier-one.port     && cp -v etc/default.passwd etc/passwd" did not complete successfully: exit code: 1
镜像打包失败，请重试

**Comment by jueinin** [comment]
@xubiaolin

**Comment by supermikimiki** [comment]
提供一个临时解决方法：
自己配置一个http代理（我用的clash）；
然后修改deploy.sh第57行为
`  docker build --build-arg "HTTP_PROXY=http://127.0.0.1:7890/" --build-arg "HTTPS_PROXY=http://127.0.0.1:7890/" --build-arg "NO_PROXY=localhost,127.0.0.1" --no-cache --build-arg ZT_PORT=$port --network host -t $imageName .`
@jueinin

**Comment by jueinin** [comment]
牛啊  我来试试看 @supermikimiki

**Comment by Cappuccino-y** [comment]
可以自己搭建代理后在dockerfile里删掉ghself.markxu.online的前缀就行了
