### ISSUE TITLE
使用个别家的服务器无法加入自定义的planet

### ISSUE THREAD

**Issue by coolkidhai** [xubiaolin/docker-zerotier-planet#78]
同样的配置之前在几家大运营商的vps下可以加入，这次换了一家同样操作无法加入网络，join 网络显示200 成功，但是后台实际没有看到新设备加入。
listpeers
显示- -1 - PLANET
因为这个服务器买了1年。请求解决，怀疑是这个运营商做什么限制，不知道怎么提工单
服务器9993端口是能telnet通的

**Comment by xubiaolin** [comment]
服务器换个端口，用9994，或者19994试试

**Comment by coolkidhai** [comment]
> 服务器换个端口，用9994，或者19994试试

好的，我去试试，其实奇怪是哪一方做的限制。我planet在大陆，vps是hk的。
