### ISSUE TITLE
服务端搭建在内网环境下是否可行

### ISSUE THREAD

**Issue by simplove** [xubiaolin/docker-zerotier-planet#82]
服务器搭建在内网环境下
端口用的59993
在路由器上面有映射TCP/UDP的59993端口，公网IP是电信固定IP 202.****
openwrt就是加入不了网络
换一台甲骨文的服务器就可以加入，说明不是openwrt的问题
在openwrt的网络下确实看到有向202.***的59993发送UDP请求

奇怪

在安装的时候也正确认别到公网IP了的

破案了。
内网是爱快+op的组合，op上开了科学上网服务
关掉科学上网服务就可以了，或者把内网那台服务器的网关改成爱快的IP，不让它走科学服务也可以通。

**Comment by xubiaolin** [comment]
可以，公网本质上也是个大内网
