### ISSUE TITLE
按装输入完iP后， 出错。 

### ISSUE THREAD

**Issue by 66eagle** [xubiaolin/docker-zerotier-planet#86]
安装不成功：

y
清除原有内容
rm: cannot remove ‘/opt/planet’: No such file or directory
Error response from daemon: No such container: zerotier-planet
Error response from daemon: No such container: zerotier-planet
Error response from daemon: No such image: zerotier-planet:latest
打包镜像
flag provided but not defined: --network
See 'docker build --help'.
启动服务
./deploy.sh: line 50: lsof: command not found
Unable to find image 'zerotier-planet:latest' locally
Pulling repository docker.io/library/zerotier-planet
docker: Error: Status 410 trying to pull repository library/zerotier-planet: "<html>\r\n<head><title>410 Gone</title></head>\r\n<body>\r\n<center><h1>410 Gone</h1></center>\r\n<hr><center>openresty</center>\r\n</body>\r\n</html>\r\n".
See 'docker run --help'.
Error response from daemon: No such container: zerotier-planet

不知道怎么办。

**Comment by xubiaolin** [comment]
docker版本太低了，换个新版本docker
