### ISSUE TITLE
为何plant会连接很多美国的IP

### ISSUE THREAD

**Issue by simplove** [xubiaolin/docker-zerotier-planet#87]
![](https://img.233444.xyz/imgs/2023/08/fdcecd2190153a97.png)

**Comment by wranglerlmx** [comment]
我也是想用先来看看，这是非官方的项目吧，不排除有私活不安全，看到这里我决定还是不用这个了～

**Comment by xubiaolin** [comment]
代码都是官方的，全部都是开源的，上面的图片是其他app访问了9993端口罢了，和zerotier没有关系，自建planet推荐使用9994端口

> 我也是想用先来看看，这是非官方的项目吧，不排除有私活不安全，看到这里我决定还是不用这个了～

**Comment by xubiaolin** [comment]
看起来像是优酷的软件在搞花活，代码都是开源的，安全无毒，可以审查

**Comment by simplove** [comment]
> 代码都是官方的，全部都是开源的，上面的图片是其他app访问了9993端口罢了，和zerotier没有关系，自建planet推荐使用9994端口
> 
> > 我也是想用先来看看，这是非官方的项目吧，不排除有私活不安全，看到这里我决定还是不用这个了～

明显不是，那个截图是我在爱快路由器上看到的，优酷土豆是它识别不准。
我一台linux主机，就只是安装了zerotier的docker，又不是网关，怎么会有优酷土豆的应用了？
再说我用的端口不是9993，而是高位的50000以上端口。

问题应该是出在这 [#82](https://github.com/xubiaolin/docker-zerotier-planet/issues/82)
它访问的应该是zerotier官方的节点服务器
