### ISSUE TITLE
请问docker中的zerotier无法加入网络吗？

### ISSUE THREAD

**Issue by fantasy0v0** [xubiaolin/docker-zerotier-planet#93]
加入网络后提示500，网卡也没有增加
![image](https://github.com/xubiaolin/docker-zerotier-planet/assets/9549027/24d3e00a-ff6c-484b-8cc8-081510d8f404)

ztncui里面虽然多出来了一个controller，但是其他节点访问不了。
![image](https://github.com/xubiaolin/docker-zerotier-planet/assets/9549027/8113a222-b09e-4b70-bdf3-ea71ffe8c169)

**Comment by xubiaolin** [comment]
500是因为你映射网卡设备，可以参考Q&A的PVE7没有创建网络的问题
