### ISSUE TITLE
能否使用最新版本的ZeroTier构建呢，ui界面进去显示是1.10而不是。1.12。

### ISSUE THREAD

**Issue by WantSleep0419** [xubiaolin/docker-zerotier-planet#94]

**Comment by XaYoCn** [comment]
同 1.10.2

**Comment by MINGERTAI** [comment]
希望大佬更新

**Comment by wekingchen** [comment]
看上去抓取的是ZeroTier最新的代码，但是编译出来确是1.10.2的版本，大佬可以看看原因吗？

**Comment by MINGERTAI** [comment]
希望大佬看看原因谢谢了，另外请教一下。是不是内置了moon服务

**Comment by WantSleep0419** [comment]
想要1.12，还是自己编译搭建服务器，步骤并不复杂

**Comment by xubiaolin** [comment]
最新代码已改为从官方最新代码编译zerotier了，请使用最新的脚本部署

**Comment by XaYoCn** [comment]
> 最新代码已改为从官方最新代码编译zerotier了，请使用最新的脚本部署
大佬，最新脚本怎么获取？
使用 git clone https://github.com/xubiaolin/docker-zerotier-planet.git 安装还是1.10.2，使用全新全新debian12.2系统安装
谢谢

**Comment by wekingchen** [comment]
> > 最新代码已改为从官方最新代码编译zerotier了，请使用最新的脚本部署
> 
> 大佬，最新脚本怎么获取？ 使用 git clone https://github.com/xubiaolin/docker-zerotier-planet.git 安装还是1.10.2，使用全新debian12.2系统安装 谢谢

试下用这个安装呢？https://github.com/wekingchen/docker-zerotier-planet

**Comment by XaYoCn** [comment]
> > > 最新代码已改为从官方最新代码编译zerotier了，请使用最新的脚本部署
> > 
> > 
> > 大佬，最新脚本怎么获取？ 使用 git clone https://github.com/xubiaolin/docker-zerotier-planet.git 安装还是1.10.2，使用全新debian12.2系统安装 谢谢
> 
> 试下用这个安装呢？https://github.com/wekingchen/docker-zerotier-planet

试了几次都提示 “镜像打包失败，请重试，国内机器打包容易失败，请多试几次”

用xubiaolin原版没这个问题

**Comment by xubiaolin** [comment]
大家不要着急，已经在连夜更新代码了

**Comment by XaYoCn** [comment]
> > > 最新代码已改为从官方最新代码编译zerotier了，请使用最新的脚本部署
> > 
> > 
> > 大佬，最新脚本怎么获取？ 使用 git clone https://github.com/xubiaolin/docker-zerotier-planet.git 安装还是1.10.2，使用全新debian12.2系统安装 谢谢
> 
> 试下用这个安装呢？https://github.com/wekingchen/docker-zerotier-planet

上午重试了一下，一次安装成功 1.12.2，就是安装时间稍长。

**Comment by wekingchen** [comment]
因为要本地编译，所以时间稍长，你是国内还是国外服务器呢？

> > > > 最新代码已改为从官方最新代码编译zerotier了，请使用最新的脚本部署
> > > 
> > > 
> > > 大佬，最新脚本怎么获取？ 使用 git clone https://github.com/xubiaolin/docker-zerotier-planet.git 安装还是1.10.2，使用全新debian12.2系统安装 谢谢
> > 
> > 
> > 试下用这个安装呢？https://github.com/wekingchen/docker-zerotier-planet
> 
> 上午重试了一下，一次安装成功 1.12.2，就是安装时间稍长。

终于有人成功了，哈哈。因为要在本地编译，所以时间稍长，你是国内还是国外服务器呢？

**Comment by XaYoCn** [comment]
> 因为要本地编译，所以时间稍长，你是国内还是国外服务器呢？
> 
> > > > > 最新代码已改为从官方最新代码编译zerotier了，请使用最新的脚本部署
> > > > 
> > > > 
> > > > 大佬，最新脚本怎么获取？ 使用 git clone https://github.com/xubiaolin/docker-zerotier-planet.git 安装还是1.10.2，使用全新debian12.2系统安装 谢谢
> > > 
> > > 
> > > 试下用这个安装呢？https://github.com/wekingchen/docker-zerotier-planet
> > 
> > 
> > 上午重试了一下，一次安装成功 1.12.2，就是安装时间稍长。
> 
> 终于有人成功了，哈哈。因为要在本地编译，所以时间稍长，你是国内还是国外服务器呢？

国内的，2C4G

**Comment by MINGERTAI** [comment]
```
RUN ZEROTIER_ONE_VERSION=`curl -s "https://api.github.com/repos/zerotier/ZeroTierOne/releases" | jq '.[0].tag_name'` && \
    curl https://codeload.github.com/zerotier/ZeroTierOne/tar.gz/refs/tags/${ZEROTIER_ONE_VERSION} --output /tmp/ZeroTierOne.tar.gz \
    && tar fxz /tmp/ZeroTierOne.tar.gz \
    && mv /app/ZeroTierOne-* /app/ZeroTierOne \
    && rm -rf /tmp/ZeroTierOne.tar.gz \
    && cd /app/ZeroTierOne \
    && make ZT_SYMLINK=1 \
    && make install
```
编译时，变量这块出错过不去，忘懂的帮看一下需要怎样修改
抄于 https://github.com/sbilly/docker-zerotier-controller/blob/main/Dockerfile

**Comment by xubiaolin** [comment]
免编译镜像测试已通过，这两天会整理代码和镜像，大家不用折腾编译了

**Comment by MINGERTAI** [comment]
谢谢了

**Comment by MINGERTAI** [comment]
planet文件，可以在命令下随机生成是吧?

**Comment by xubiaolin** [comment]
> planet文件，可以在命令下随机生成是吧?

启动镜像的时候会自动生成，ip和端口可以在启动镜像的时候指定，否则自动获取

**Comment by WantSleep0419** [comment]
大佬，按照你readme的步骤去走docker安装完成后还是显示版本为1.10.2，我看您在评论中说改为1.12.2了，是什么原因呢？

**Comment by WantSleep0419** [comment]
嗯嗯，期待一下，您的docker装起来非常迅速👍👍👍👍

**Comment by xubiaolin** [comment]
ZT_PORT=9994
API_PORT=3443
FILE_PORT=3000

docker run -d --name myztplanet\
     -p ${ZT_PORT}:${ZT_PORT} \
     -p ${ZT_PORT}:${ZT_PORT}/udp \
     -p ${API_PORT}:${API_PORT}\
     -p ${FILE_PORT}:${FILE_PORT} \
     -e ZT_PORT=${ZT_PORT} \
     -e API_PORT=${API_PORT} \
     -e FILE_SERVER_PORT=${FILE_PORT} \
     -v /data/zerotier/dist:/app/dist \
     -v /data/zerotier/ztncui:/app/ztncui\
     -v /data/zerotier/one:/var/lib/zerotier-one\
     -v /data/config:/app/config\
     xubiaolin/zerotier-planet:latest

**Comment by xubiaolin** [comment]
最新代码已发布，支持了1.12.2版本
